import { AMB } from '../index.js';
import { createDemoReportDialog } from './utils/demo-report-dialog.js';
import { createDemoCheckboxFormatter } from './utils/demo-checkbox.js';
import { createDemoColumnGuide } from './utils/demo-column-guide.js';

const formatArchivedCheckbox = createDemoCheckboxFormatter({ checkedValue: 'Y' });

const countRowsByState = (report, state) => {
    return report.rows.filter(row => row.state === state).length;
};

const buildPayloadReport = payload => [
    `Inserted rows: ${payload.changes.inserted.length}`,
    `Updated rows: ${payload.changes.updated.length}`,
    `Deleted rows: ${payload.changes.deleted.length}`,
    `Has changes: ${payload.hasChanges}`,
    `Can save: ${payload.canSave}`
];

const buildStateReport = report => [
    `Total rows: ${report.totalRows}`,
    `Clean rows: ${countRowsByState(report, 'clean')}`,
    `New rows: ${countRowsByState(report, 'new')}`,
    `Modified rows: ${countRowsByState(report, 'modified')}`,
    `Deleted rows: ${countRowsByState(report, 'deleted')}`,
    `Saved rows: ${countRowsByState(report, 'saved')}`,
    `Error rows: ${report.errorRowsCount}`,
    `Can save: ${report.validChangedRowsCount > 0 && !report.hasErrors}`
];

export default function basicCrud(app) {
    let nextNoteNumber = 11;
    const initialData = [
        { id: 'NT-001', title: 'Welcome note', tag: 'intro', archived: 'N' },
        { id: 'NT-002', title: 'Shortcut idea', tag: 'idea', archived: 'N' },
        { id: 'NT-003', title: 'Release checklist', tag: 'todo', archived: 'Y' },
        { id: 'NT-004', title: 'Documentation update', tag: 'docs', archived: 'N' },
        { id: 'NT-005', title: 'Meeting reminder', tag: 'reminder', archived: 'N' },
        { id: 'NT-006', title: 'Deployment notes', tag: 'release', archived: 'Y' },
        { id: 'NT-007', title: 'Support handoff', tag: 'support', archived: 'N' },
        { id: 'NT-008', title: 'Review summary', tag: 'review', archived: 'N' },
        { id: 'NT-009', title: 'Archive policy', tag: 'archive', archived: 'Y' },
        { id: 'NT-010', title: 'Planning checklist', tag: 'planning', archived: 'N' }
    ];

    const getNextNoteId = () => {
        const value = String(nextNoteNumber).padStart(3, '0');

        nextNoteNumber += 1;
        return `NT-${value}`;
    };

    app.innerHTML = `
        <h2 data-i18n="examples.basicCrud.title">Basic CRUD</h2>
        <p class="demo-note" data-i18n="examples.basicCrud.intro">Edit rows, add records, mark items for deletion, and inspect the save payload generated by AMB Grid.</p>
        ${createDemoColumnGuide({
            summary: 'Basic CRUD behavior',
            summaryKey: 'examples.basicCrud.detailsTitle',
            points: [
                { title: 'Add and edit', titleKey: 'examples.basicCrud.point1Title', description: 'Add Row creates a local row. Editing an existing row marks it as modified.', descriptionKey: 'examples.basicCrud.detail1' },
                { title: 'Row states', titleKey: 'examples.basicCrud.point2Title', description: 'The State column shows which records are new, modified, deleted, or saved.', descriptionKey: 'examples.basicCrud.detail2' },
                { title: 'Delete and rollback', titleKey: 'examples.basicCrud.point3Title', description: 'Existing rows are marked for deletion; unsaved new rows can be removed directly.', descriptionKey: 'examples.basicCrud.detail3' },
                { title: 'Payload', titleKey: 'examples.basicCrud.point4Title', description: 'Show payload separates inserted, updated, and deleted records.', descriptionKey: 'examples.basicCrud.detail4' },
                { title: 'Validate and save', titleKey: 'examples.basicCrud.point5Title', description: 'Save validates current changes and realigns valid row states after application confirmation.', descriptionKey: 'examples.basicCrud.detail5' }
            ],
            columns: [
                { title: 'ID', titleKey: 'guides.basic.id.title', badge: 'PERSISTENT', description: 'Persistent identifier assigned to a saved note.', descriptionKey: 'guides.basic.id.description' },
                { title: 'Temp ID', titleKey: 'guides.basic.tempId.title', badge: 'TEMP', description: 'Temporary identifier used by a new row before it is saved.', descriptionKey: 'guides.basic.tempId.description' },
                { title: 'Row No.', titleKey: 'guides.basic.rowNumber.title', badge: 'ORDER', description: 'Stable application row number used by reports and feedback.', descriptionKey: 'guides.basic.rowNumber.description' },
                { title: 'State', titleKey: 'guides.basic.state.title', badge: 'CRUD', description: 'Shows clean, new, modified, deleted, or saved lifecycle state.', descriptionKey: 'guides.basic.state.description' },
                { title: 'Title', titleKey: 'guides.basic.title.title', badge: 'TEXT', description: 'Required trimmed text with a minimum length of 3 characters.', descriptionKey: 'guides.basic.title.description' },
                { title: 'Tag', titleKey: 'guides.basic.tag.title', badge: 'TEXT', description: 'Required lowercase text, letters only, up to 12 characters.', descriptionKey: 'guides.basic.tag.description' },
                { title: 'Archived', titleKey: 'guides.basic.archived.title', badge: 'BOOLEAN', description: 'Editable checkbox stored with the application values Y and N.', descriptionKey: 'guides.basic.archived.description' }
            ]
        })}
        <div class="demo-table-workbench">
            <div id="basic-table" class="demo-business-grid demo-business-grid--viewport"></div>
        </div>
    `;

    const demo = AMB.table({
        selector: '#basic-table',
        deleteColumn: {
            enabled: true,
            confirmDeleteMessage: 'Delete this note?',
            confirmRollbackMessage: 'Rollback this note?',
            confirmRemoveNewMessage: 'Remove this new note?'
        },
        selectionColumn: {
            enabled: true,
            mode: 'multiple'
        },
        toolbar: {
            buttons: [
                'add',
                'reload',
                'save',
                'payload',
                {
                    id: 'report',
                    label: 'Show report',
                    onClick: handleShowReport
                },
                {
                    id: 'selected',
                    label: 'Show selected',
                    onClick: handleShowSelected
                }
            ],
            onAdd: handleAdd,
            onReload: handleReload,
            onSave: handleSave,
            onPayload: handleShowPayload
        },
        search: {
            enabled: true,
            placeholder: 'Search notes...',
            filters: {
                enabled: true
            }
        },
        data: initialData.map(row => ({ ...row })),
        layout: 'fitColumns',
        columns: [
            { title: 'ID', field: 'id', minWidth: 75, widthGrow: 0.55 },
            { title: 'Temp ID', field: '_ambTempId', minWidth: 105, widthGrow: 0.75 },
            { title: 'Row No.', field: '_ambRowNumber', minWidth: 78, widthGrow: 0.55 },
            { title: 'State', field: '_state', minWidth: 88, widthGrow: 0.65 },
            {
                title: 'Title',
                field: 'title',
                minWidth: 140,
                widthGrow: 1.8,
                editor: AMB.editors.text({ trim: true }),
                required: true,
                requiredMessage: 'Title is required',
                validation: {
                    minLength: {
                        value: 3,
                        message: 'Title must be at least 3 characters'
                    }
                }
            },
            {
                title: 'Tag',
                field: 'tag',
                minWidth: 100,
                widthGrow: 1,
                editor: AMB.editors.text({ lowercase: true, trim: true }),
                required: true,
                requiredMessage: 'Tag is required',
                validation: {
                    pattern: {
                        regex: /^[a-z]+$/,
                        message: 'Tag must contain lowercase letters only'
                    },
                    maxLength: {
                        value: 12,
                        message: 'Tag must be at most 12 characters'
                    }
                }
            },
            {
                title: 'Archived',
                field: 'archived',
                minWidth: 92,
                widthGrow: 0.55,
                hozAlign: 'center',
                cssClass: 'demo-business-checkbox-cell',
                formatter: formatArchivedCheckbox,
                editor: AMB.editors.checkbox({
                    checkedValue: 'Y',
                    uncheckedValue: 'N',
                    checkedLabel: '',
                    uncheckedLabel: ''
                })
            }
        ]
    });

    const { crud } = demo;
    const reportDialog = createDemoReportDialog();
    const partialSaveDialog = new AMB.ConfirmDialog({
        title: 'Save valid rows?'
    });
    const originalDestroy = demo.destroy.bind(demo);
    const hasValidChanges = payload => {
        return payload.changes.inserted.length > 0
            || payload.changes.updated.length > 0
            || payload.changes.deleted.length > 0;
    };
    const getInvalidRowsMessage = validateResult => {
        const invalidRows = validateResult.rows.filter(row => !row.isValid);

        if (!invalidRows.length) return '';

        return invalidRows.map(row => {
            const rowLabel = row.rowNumber === null || row.rowNumber === undefined
                ? 'unknown'
                : row.rowNumber;
            const fields = row.errors.map(error => error.field).join(', ');

            return `Row ${rowLabel}: ${fields}`;
        }).join('\n');
    };

    demo.destroy = () => {
        reportDialog.destroy();
        partialSaveDialog.destroy();
        originalDestroy();
    };

    function handleAdd() {
        demo.feedback.clear();
        return crud.addRow({ id: null, title: '', tag: '', archived: 'N' });
    }

    async function handleReload() {
        nextNoteNumber = 11;
        await demo.table.setData(initialData.map(row => ({ ...row })));
        demo.feedback.show({
            type: 'success',
            message: 'Data reloaded.'
        });
    }

    function handleShowPayload({ payload }) {
        reportDialog.open({
            title: 'Save payload',
            reportLines: buildPayloadReport(payload),
            jsonData: payload
        });
    }

    function handleShowReport() {
        const stateReport = crud.getStateReport();

        reportDialog.open({
            title: 'Basic CRUD report',
            reportLines: buildStateReport(stateReport),
            jsonData: stateReport
        });
    }

    function handleShowSelected() {
        const selectedRows = demo.getSelectedRows();
        const selectedIds = selectedRows
            .map(row => row.id || row._ambTempId)
            .filter(Boolean);

        reportDialog.open({
            title: 'Selected rows',
            reportLines: [
                `Selected rows: ${selectedRows.length}`,
                `Selected IDs: ${selectedIds.length ? selectedIds.join(', ') : 'none'}`
            ],
            jsonData: selectedRows
        });
    }

    async function handleSave() {
        const validateResult = crud.validateAll();
        const payload = crud.getSavePayload();

        if (!validateResult.isValid) {
            if (!hasValidChanges(payload)) {
                demo.feedback.show({
                    type: 'warning',
                    message: 'There are no valid changes to save.'
                });
                return;
            }

            const invalidRowsMessage = getInvalidRowsMessage(validateResult);
            const confirmed = await partialSaveDialog.confirm({
                message: [
                    'Some rows contain errors and will not be saved. Do you want to save only valid rows?',
                    invalidRowsMessage ? `Invalid rows:\n${invalidRowsMessage}` : ''
                ].filter(Boolean).join('\n\n')
            });

            if (!confirmed) {
                demo.feedback.show({
                    type: 'info',
                    message: 'Save cancelled.'
                });
                return;
            }
        }

        if (!hasValidChanges(payload)) {
            demo.feedback.show({
                type: 'info',
                message: 'There are no changes to save.'
            });
            return;
        }

        const generatedIds = payload.changes.inserted
            .filter(item => {
                return item._ambTempId
                    && (item.id === null || item.id === undefined || item.id === '');
            })
            .map(item => ({
                tempId: item._ambTempId,
                id: getNextNoteId()
            }));
        crud.applyBackendIds(generatedIds);
        crud.markValidChangesSaved();
        demo.feedback.show({
            type: 'success',
            message: 'Changes saved successfully.'
        });
    }

    return demo;
}
