export const publicExampleTranslations = {
    it: {
        'examples.basicCrud.title': 'Basic CRUD',
        'examples.basicCrud.description': 'CRUD minimo con toolbar e payload applicativo.',
        'examples.basicCrud.intro': 'Basic CRUD mostra il ciclo di vita essenziale delle righe: modifica dei record esistenti, aggiunta di nuove righe, validazione, eliminazione o rollback e generazione del payload di salvataggio.',
        'examples.basicCrud.detailsTitle': 'Come funziona Basic CRUD',
        'examples.basicCrud.point1Title': 'Aggiunta e modifica',
        'examples.basicCrud.detail1': 'Add Row crea una riga locale. Modificando una riga esistente, AMB Grid la marca come modified.',
        'examples.basicCrud.point2Title': 'Stati riga',
        'examples.basicCrud.detail2': 'La colonna State mostra quali record sono new, modified, deleted o saved.',
        'examples.basicCrud.point3Title': 'Eliminazione e rollback',
        'examples.basicCrud.detail3': 'Le righe esistenti vengono marcate per l’eliminazione; quelle nuove non salvate possono essere rimosse direttamente.',
        'examples.basicCrud.point4Title': 'Payload',
        'examples.basicCrud.detail4': 'Show payload separa chiaramente record inserted, updated e deleted.',
        'examples.basicCrud.point5Title': 'Validazione e salvataggio',
        'examples.basicCrud.detail5': 'Save valida le modifiche correnti e riallinea gli stati validi dopo la conferma applicativa.',
        'examples.validation.title': 'Validation',
        'examples.validation.description': 'Regole campo, errori riga e report di validazione.',
        'examples.validation.intro': 'Modifica i dati oppure crea anomalie intenzionali per osservare errori, report e ripristino.',
        'examples.validation.detailsTitle': 'Come funziona la validazione',
        'examples.validation.point1Title': 'Regole sui campi',
        'examples.validation.detail1': 'I campi mostrano regole required, unique, lunghezza, pattern e formato.',
        'examples.validation.point2Title': 'Errori visibili',
        'examples.validation.detail2': 'Lasciando una cella modificata non valida, il feedback resta associato alla cella e alla riga.',
        'examples.validation.point3Title': 'Dati validi e non validi',
        'examples.validation.detail3': 'Create anomalies rende evidente il confronto; il report elenca le regole non superate.',
        'examples.validation.point4Title': 'Payload e salvataggio',
        'examples.validation.detail4': 'Le righe modificate non valide non entrano nella parte del payload pronta al salvataggio.',
        'examples.validation.point5Title': 'Correzione',
        'examples.validation.detail5': 'Correggi un valore evidenziato e valida di nuovo per rimuovere l’errore.',
        'examples.autocomplete.title': 'Autocomplete',
        'examples.autocomplete.description': 'Suggerimenti controllati per campi testuali business.',
        'examples.autocomplete.intro': 'Digita nei campi per filtrare suggerimenti e confrontare valori controllati e liberi.',
        'examples.autocomplete.detailsTitle': 'Come funziona autocomplete',
        'examples.autocomplete.point1Title': 'Suggerimenti',
        'examples.autocomplete.detail1': 'Le opzioni compatibili compaiono e si restringono durante la digitazione.',
        'examples.autocomplete.point2Title': 'Valori strict',
        'examples.autocomplete.detail2': 'I campi Department richiedono un valore presente nella lista fornita.',
        'examples.autocomplete.point3Title': 'Valori liberi',
        'examples.autocomplete.detail3': 'Tag e city accettano anche valori personalizzati non presenti nei suggerimenti.',
        'examples.autocomplete.point4Title': 'Tastiera',
        'examples.autocomplete.detail4': 'Usa le frecce per navigare i suggerimenti e conferma senza lasciare la tastiera.',
        'examples.autocomplete.point5Title': 'Valore confermato',
        'examples.autocomplete.detail5': 'L’opzione confermata diventa il valore della cella usato da validazione e payload CRUD.',
        'examples.multifieldLookup.title': 'Multifield lookup',
        'examples.multifieldLookup.description': 'Lookup che aggiorna più campi da un record scelto.',
        'examples.multifieldLookup.intro': 'Municipality è il campo master modificabile. Digita per usare l’autocomplete oppure usa il pulsante di ricerca per aprire il lookup completo.',
        'examples.multifieldLookup.detailsTitle': 'Come funziona il multifield lookup',
        'examples.multifieldLookup.point1Title': 'Selezione record',
        'examples.multifieldLookup.detail1': 'Digita per usare l’autocomplete oppure apri il lookup completo con il pulsante di ricerca e scegli un record.',
        'examples.multifieldLookup.point2Title': 'Campo master',
        'examples.multifieldLookup.detail2': 'Comune è il campo master azionabile; i campi dipendenti restano readonly.',
        'examples.multifieldLookup.point3Title': 'Campi dipendenti',
        'examples.multifieldLookup.detail3': 'Provincia, Regione, CAP, codice ISTAT e codice catastale si aggiornano insieme.',
        'examples.multifieldLookup.point4Title': 'Ricerca',
        'examples.multifieldLookup.detail4': 'Cerca nel dataset per restringere i Comuni disponibili prima della selezione.',
        'examples.multifieldLookup.point5Title': 'Dati coerenti',
        'examples.multifieldLookup.detail5': 'La selezione di un unico record evita combinazioni incoerenti tra valori dipendenti.',
        'examples.multifieldLookup.warning': 'Avviso dati demo:',
        'examples.multifieldLookup.warningText': 'Questo dataset è fornito esclusivamente a scopo dimostrativo. Potrebbe essere incompleto, non aggiornato o inesatto. Non usarlo come fonte ufficiale in sistemi di produzione.',
        'examples.rowStates.title': 'Row states',
        'examples.rowStates.description': 'Stati riga, rollback, delete e report tecnici.',
        'examples.rowStates.intro': 'Usa toolbar e colonna delete per seguire il ciclo di vita applicativo di ogni riga.',
        'examples.rowStates.detailsTitle': 'Come funzionano gli stati riga',
        'examples.rowStates.point1Title': 'Ciclo di vita',
        'examples.rowStates.detail1': 'clean è invariata, new è stata aggiunta localmente e modified differisce dai dati originali.',
        'examples.rowStates.point2Title': 'Eliminazione',
        'examples.rowStates.detail2': 'deleted marca una riga esistente; una riga new non salvata viene rimossa direttamente.',
        'examples.rowStates.point3Title': 'Salvataggio',
        'examples.rowStates.detail3': 'Save elabora le modifiche valide e rende visibile saved dopo la conferma applicativa.',
        'examples.rowStates.point4Title': 'Rollback',
        'examples.rowStates.detail4': 'Rollback ripristina i valori originali e riporta una riga modificata a clean.',
        'examples.rowStates.point5Title': 'Report',
        'examples.rowStates.detail5': 'Report riepiloga stati ed errori; Row numbers mostra i riferimenti stabili usati dal feedback.',
        'examples.dates.title': 'Dates',
        'examples.dates.description': 'Input data, formati multipli, validazione e selezione tramite datepicker.',
        'examples.dates.intro': 'Confronta input manuale, formati data multipli, range di validazione e modalità datepicker reali.',
        'examples.dates.detailsTitle': 'Come funzionano le date',
        'examples.dates.detailsText': 'Formato, editor, visualizzazione, validazione e range restano allineati tramite configurazioni data condivise.',
        'examples.dates.point1Title': 'Formati multipli',
        'examples.dates.detail1': 'Date manuali, ISO, compatte e con trattino usano il formato dichiarato.',
        'examples.dates.point2Title': 'Manuale e datepicker',
        'examples.dates.detail2': 'Alcune celle accettano la digitazione, altre aggiungono il calendario o aprono direttamente il picker.',
        'examples.dates.point3Title': 'Validazione visibile',
        'examples.dates.detail3': 'I valori digitati non validi restano visibili per mostrare errori di sintassi, calendario o range.',
        'examples.dates.point4Title': 'Range consentito',
        'examples.dates.detail4': 'Tutte le date devono essere comprese tra 01/01/2025 e 31/12/2027.',
        'examples.dates.validate': 'Valida date',
        'examples.dates.validateTitle': 'Valida i valori data',
        'examples.parsers.title': 'Parsers',
        'examples.parsers.description': 'Normalizza i valori inseriti in formati prevedibili per il payload.',
        'examples.parsers.intro': 'Modifica un valore visuale e osserva la rappresentazione normalizzata prodotta per un payload prevedibile.',
        'examples.parsers.detailsTitle': 'Come funzionano i parser',
        'examples.parsers.detailsText': 'I parser normalizzano valori visuali in forme orientate al backend, ma non sostituiscono validazione e regole business.',
        'examples.parsers.point1Title': 'Normalizzazione',
        'examples.parsers.detail1': 'Ogni riga applica un parser pubblico AMB al valore Input modificato.',
        'examples.parsers.point2Title': 'Forma del payload',
        'examples.parsers.detail2': 'Parsed value mostra la rappresentazione prevedibile destinata al payload applicativo.',
        'examples.parsers.point3Title': 'Validazione separata',
        'examples.parsers.detail3': 'Il parser trasforma la sintassi; validazione e regole business decidono se il dato è accettabile.',
        'examples.parsers.point4Title': 'Parser pubblici',
        'examples.parsers.detail4': "AMB Grid fornisce parser pronti all'uso per trasformazioni comuni del payload, come numeri, date, orari, booleani e valori null. Le relative opzioni possono essere configurate in base al contratto applicativo.",
        'examples.parsers.point5Title': 'Parser personalizzati',
        'examples.parsers.detail5': "Quando una regola business richiede una trasformazione specifica, AMB.parsers.custom(parseFn) permette all'applicazione di definire una propria logica di parsing riutilizzabile.",
        'examples.columnCalculations.title': 'Column calculations',
        'examples.columnCalculations.description': 'Calcoli aggregati direttamente sulle colonne: count, unique, sum, avg, min e max.',
        'examples.columnCalculations.intro': 'Modifica i valori business e osserva ogni aggregato aggiornarsi nella propria colonna.',
        'examples.columnCalculations.detailsTitle': 'Come funzionano i calcoli di colonna',
        'examples.columnCalculations.detailsText': 'La calculation row presenta gli aggregati accanto ai dati cui si riferiscono.',
        'examples.columnCalculations.point1Title': 'Propria colonna',
        'examples.columnCalculations.detail1': 'Ogni calcolo riceve soltanto i valori della colonna in cui viene mostrato.',
        'examples.columnCalculations.point2Title': 'Aggiornamento',
        'examples.columnCalculations.detail2': 'Modifica, aggiunta, eliminazione e rollback aggiornano gli aggregati sulle righe attive.',
        'examples.columnCalculations.point3Title': 'Riga integrata',
        'examples.columnCalculations.detail3': 'La calculation row mantiene gli aggregati nella grid senza riepiloghi manuali esterni.',
        'examples.columnCalculations.id': 'ID',
        'examples.columnCalculations.idCalc': 'COUNT conta il numero di righe.',
        'examples.columnCalculations.product': 'Prodotto',
        'examples.columnCalculations.productCalc': 'Il calcolo personalizzato conta i nomi prodotto che contengono "print".',
        'examples.columnCalculations.category': 'Categoria',
        'examples.columnCalculations.categoryCalc': 'UNIQUE conta le categorie distinte.',
        'examples.columnCalculations.quantity': 'Quantità',
        'examples.columnCalculations.quantityCalc': 'SUM somma le quantità di tutte le righe.',
        'examples.columnCalculations.unitPrice': 'Prezzo unitario',
        'examples.columnCalculations.unitPriceCalc': 'AVG calcola il prezzo unitario medio.',
        'examples.columnCalculations.deliveryDays': 'Giorni consegna',
        'examples.columnCalculations.deliveryDaysCalc': 'MIN mostra il minor numero di giorni di consegna.',
        'examples.columnCalculations.score': 'Punteggio',
        'examples.columnCalculations.scoreCalc': 'MAX mostra il punteggio più alto.'
    },
    en: {
        'examples.basicCrud.title': 'Basic CRUD',
        'examples.basicCrud.description': 'Minimal CRUD with toolbar and application payload.',
        'examples.basicCrud.intro': 'Basic CRUD demonstrates the essential row lifecycle: editing existing records, adding new rows, validation, deletion or rollback, and generation of the save payload.',
        'examples.basicCrud.detailsTitle': 'How Basic CRUD works',
        'examples.basicCrud.point1Title': 'Add and edit',
        'examples.basicCrud.detail1': 'Add Row creates a local row. Editing an existing row makes AMB Grid mark it as modified.',
        'examples.basicCrud.point2Title': 'Row states',
        'examples.basicCrud.detail2': 'The State column shows which records are new, modified, deleted, or saved.',
        'examples.basicCrud.point3Title': 'Delete and rollback',
        'examples.basicCrud.detail3': 'Existing rows are marked for deletion; unsaved new rows can be removed directly.',
        'examples.basicCrud.point4Title': 'Payload',
        'examples.basicCrud.detail4': 'Show payload clearly separates inserted, updated, and deleted records.',
        'examples.basicCrud.point5Title': 'Validate and save',
        'examples.basicCrud.detail5': 'Save validates current changes and realigns valid row states after application confirmation.',
        'examples.validation.title': 'Validation',
        'examples.validation.description': 'Field rules, row errors, and validation reports.',
        'examples.validation.intro': 'Edit data or create intentional anomalies to inspect errors, reports, and reset behavior.',
        'examples.validation.detailsTitle': 'How validation works',
        'examples.validation.point1Title': 'Field rules',
        'examples.validation.detail1': 'Fields demonstrate required, unique, length, pattern, and format rules.',
        'examples.validation.point2Title': 'Visible errors',
        'examples.validation.detail2': 'Leaving an invalid edited cell keeps feedback associated with that cell and row.',
        'examples.validation.point3Title': 'Valid and invalid data',
        'examples.validation.detail3': 'Create anomalies makes the contrast visible; the report lists the rules that failed.',
        'examples.validation.point4Title': 'Payload and save',
        'examples.validation.detail4': 'Invalid changed rows cannot enter the save-ready portion of the payload.',
        'examples.validation.point5Title': 'Correct and retry',
        'examples.validation.detail5': 'Correct a highlighted value and validate again to clear its error.',
        'examples.autocomplete.title': 'Autocomplete',
        'examples.autocomplete.description': 'Controlled suggestions for business text fields.',
        'examples.autocomplete.intro': 'Type in the fields to filter suggestions and compare controlled and free values.',
        'examples.autocomplete.detailsTitle': 'How autocomplete works',
        'examples.autocomplete.point1Title': 'Suggestions',
        'examples.autocomplete.detail1': 'Matching options appear and narrow while you type.',
        'examples.autocomplete.point2Title': 'Strict values',
        'examples.autocomplete.detail2': 'Department fields require a value from the supplied list.',
        'examples.autocomplete.point3Title': 'Free values',
        'examples.autocomplete.detail3': 'Tag and city also accept custom values outside the suggestions.',
        'examples.autocomplete.point4Title': 'Keyboard',
        'examples.autocomplete.detail4': 'Use the arrow keys to navigate suggestions and confirm without leaving the keyboard.',
        'examples.autocomplete.point5Title': 'Committed value',
        'examples.autocomplete.detail5': 'The confirmed option becomes the cell value used by validation and the CRUD payload.',
        'examples.multifieldLookup.title': 'Multifield lookup',
        'examples.multifieldLookup.description': 'Lookup that updates several fields from one selected record.',
        'examples.multifieldLookup.intro': 'Municipality is the editable master field. Type to use autocomplete or use the search button to open the complete lookup.',
        'examples.multifieldLookup.detailsTitle': 'How multifield lookup works',
        'examples.multifieldLookup.point1Title': 'Select a record',
        'examples.multifieldLookup.detail1': 'Type to use autocomplete or open the complete lookup with the search button and choose one record.',
        'examples.multifieldLookup.point2Title': 'Master field',
        'examples.multifieldLookup.detail2': 'Municipality is the actionable master field; dependent fields remain readonly.',
        'examples.multifieldLookup.point3Title': 'Dependent fields',
        'examples.multifieldLookup.detail3': 'Province, Region, Postal Code, ISTAT Code, and Cadastral Code update together.',
        'examples.multifieldLookup.point4Title': 'Search',
        'examples.multifieldLookup.detail4': 'Search the dataset to narrow the available municipalities before selection.',
        'examples.multifieldLookup.point5Title': 'Consistent data',
        'examples.multifieldLookup.detail5': 'Selecting one record prevents inconsistent combinations of dependent values.',
        'examples.multifieldLookup.warning': 'Demo data warning:',
        'examples.multifieldLookup.warningText': 'This dataset is provided for demonstration purposes only. It may be incomplete, outdated, or inaccurate. Do not use it as an official source for production systems.',
        'examples.rowStates.title': 'Row states',
        'examples.rowStates.description': 'Row states, rollback, delete, and technical reports.',
        'examples.rowStates.intro': 'Use the toolbar and delete column to follow each row through its application lifecycle.',
        'examples.rowStates.detailsTitle': 'How row states work',
        'examples.rowStates.point1Title': 'Lifecycle',
        'examples.rowStates.detail1': 'clean is unchanged, new was added locally, and modified differs from its original data.',
        'examples.rowStates.point2Title': 'Delete',
        'examples.rowStates.detail2': 'deleted marks an existing row; an unsaved new row is removed directly.',
        'examples.rowStates.point3Title': 'Save',
        'examples.rowStates.detail3': 'Save processes valid changes and exposes saved after application confirmation.',
        'examples.rowStates.point4Title': 'Rollback',
        'examples.rowStates.detail4': 'Rollback restores original values and returns an edited row to clean.',
        'examples.rowStates.point5Title': 'Report',
        'examples.rowStates.detail5': 'Report summarizes states and errors; Row numbers shows the stable references used by feedback.',
        'examples.dates.title': 'Dates',
        'examples.dates.description': 'Date input, multiple formats, validation and datepicker selection.',
        'examples.dates.intro': 'Compare manual date input, multiple formats, validation ranges, and real datepicker modes.',
        'examples.dates.detailsTitle': 'How dates work',
        'examples.dates.detailsText': 'Date format, editor behavior, display, validation, and range constraints stay aligned through shared date configurations.',
        'examples.dates.point1Title': 'Multiple formats',
        'examples.dates.detail1': 'Manual, ISO-style, compact, and dash-separated dates use their declared formats.',
        'examples.dates.point2Title': 'Manual and picker',
        'examples.dates.detail2': 'Some cells accept typing, some add a calendar button, and picker-only opens the calendar directly.',
        'examples.dates.point3Title': 'Visible validation',
        'examples.dates.detail3': 'Invalid typed values remain visible so validation can explain syntax, calendar, or range errors.',
        'examples.dates.point4Title': 'Allowed range',
        'examples.dates.detail4': 'Every date stays between 01/01/2025 and 31/12/2027.',
        'examples.dates.validate': 'Validate dates',
        'examples.dates.validateTitle': 'Validate date values',
        'examples.parsers.title': 'Parsers',
        'examples.parsers.description': 'Normalize edited values into predictable payload formats.',
        'examples.parsers.intro': 'Edit an input value and inspect the normalized representation produced for a predictable payload.',
        'examples.parsers.detailsTitle': 'How parsers work',
        'examples.parsers.detailsText': 'Parsers normalize visual values into backend-oriented shapes, but they do not replace validation or business rules.',
        'examples.parsers.point1Title': 'Normalization',
        'examples.parsers.detail1': 'Each row applies one public AMB parser to the edited Input value.',
        'examples.parsers.point2Title': 'Payload shape',
        'examples.parsers.detail2': 'Parsed value shows the predictable representation intended for application payloads.',
        'examples.parsers.point3Title': 'Separate validation',
        'examples.parsers.detail3': 'A parser transforms syntax; validation and business rules still decide whether data is acceptable.',
        'examples.parsers.point4Title': 'Built-in parsers',
        'examples.parsers.detail4': 'AMB Grid provides ready-to-use parsers for common payload transformations such as numbers, dates, times, booleans and null values. Their options can be configured for the application contract.',
        'examples.parsers.point5Title': 'Custom parsers',
        'examples.parsers.detail5': 'When a business rule needs a specific transformation, AMB.parsers.custom(parseFn) lets the application define its own reusable parsing logic.',
        'examples.columnCalculations.title': 'Column calculations',
        'examples.columnCalculations.description': 'Aggregate column calculations for count, unique, sum, avg, min, and max.',
        'examples.columnCalculations.intro': 'Edit the business values and see each aggregate update in its own column.',
        'examples.columnCalculations.detailsTitle': 'How column calculations work',
        'examples.columnCalculations.detailsText': 'The calculation row presents aggregates next to the data they describe.',
        'examples.columnCalculations.point1Title': 'Own column',
        'examples.columnCalculations.detail1': 'Every calculation receives only the values from the column where it is displayed.',
        'examples.columnCalculations.point2Title': 'Live updates',
        'examples.columnCalculations.detail2': 'Edit, add, delete, or undo and the corresponding aggregates follow the active rows.',
        'examples.columnCalculations.point3Title': 'Built-in row',
        'examples.columnCalculations.detail3': 'The calculation row keeps aggregates in the grid without external manual summaries.',
        'examples.columnCalculations.id': 'ID',
        'examples.columnCalculations.idCalc': 'COUNT returns the number of rows.',
        'examples.columnCalculations.product': 'Product',
        'examples.columnCalculations.productCalc': 'The custom calculation counts product names containing "print".',
        'examples.columnCalculations.category': 'Category',
        'examples.columnCalculations.categoryCalc': 'UNIQUE counts the distinct categories.',
        'examples.columnCalculations.quantity': 'Quantity',
        'examples.columnCalculations.quantityCalc': 'SUM adds all quantities.',
        'examples.columnCalculations.unitPrice': 'Unit price',
        'examples.columnCalculations.unitPriceCalc': 'AVG calculates the average unit price.',
        'examples.columnCalculations.deliveryDays': 'Delivery days',
        'examples.columnCalculations.deliveryDaysCalc': 'MIN returns the shortest delivery time.',
        'examples.columnCalculations.score': 'Score',
        'examples.columnCalculations.scoreCalc': 'MAX returns the highest score.'
    }
};
