export const publicExampleTranslations = {
    it: {
        'examples.basicCrud.title': 'Basic CRUD',
        'examples.basicCrud.description': 'Flusso CRUD applicativo con toolbar, validazione e payload.',
        'examples.basicCrud.intro': 'Basic CRUD mostra un flusso essenziale di gestione dati: modifica, aggiungi o elimina record, controlla il payload generato e salva le modifiche simulando la risposta del backend.',
        'examples.basicCrud.guideIntro': 'Questo esempio usa il lifecycle introdotto in Row States all’interno di un normale flusso CRUD. Qui l’attenzione è sulle operazioni applicative, sul payload e sul salvataggio. Title e Tag hanno semplici regole di validazione; l’esempio Validation successivo approfondisce errori e vincoli.',
        'examples.basicCrud.detailsTitle': 'Come funziona Basic CRUD',
        'examples.basicCrud.guideMeta': '4 campi · CRUD essenziale',
        'examples.basicCrud.point1Title': 'Gestione dei record',
        'examples.basicCrud.detail1': 'Modifica Title, Tag o Archived, aggiungi una nuova nota con Row oppure usa l’azione della riga per eliminarla o annullare le modifiche.',
        'examples.basicCrud.point2Title': 'Payload di salvataggio',
        'examples.basicCrud.detail2': 'Show payload mostra ciò che verrebbe inviato al backend, separando i record da inserire, aggiornare ed eliminare in inserted, updated e deleted.',
        'examples.basicCrud.point3Title': 'Salvataggio',
        'examples.basicCrud.detail3': 'Save controlla le modifiche pendenti e simula la risposta del backend. Le modifiche valide vengono confermate e le nuove righe ricevono un ID definitivo.',
        'examples.basicCrud.point4Title': 'Ripristino',
        'examples.basicCrud.detail4': 'Rollback annulla le modifiche della singola riga; Reload ripristina invece l’intero esempio ai dati iniziali.',
        'examples.validation.title': 'Validation',
        'examples.validation.description': 'Regole campo, errori riga e report di validazione.',
        'examples.validation.intro': 'Validation mostra regole integrate e validazioni personalizzate definite dallo sviluppatore. Modifica i dati oppure usa Create anomalies per osservare errori, report e correzione.',
        'examples.validation.introEmphasis': 'validazioni personalizzate definite dallo sviluppatore',
        'examples.validation.detailsTitle': 'Come funziona la validazione',
        'examples.validation.guideMeta': 'Regole · errori · vincoli',
        'examples.validation.point1Title': 'Regole sui campi',
        'examples.validation.detail1': 'I campi mostrano validatori integrati come required, unique, lunghezza, pattern e formato, ma possono anche usare regole custom definite dallo sviluppatore.',
        'examples.validation.detail1Emphasis': 'regole custom definite dallo sviluppatore',
        'examples.validation.point2Title': 'Errori visibili',
        'examples.validation.detail2': 'Lasciando una cella modificata non valida, il feedback resta associato alla cella e alla riga.',
        'examples.validation.point3Title': 'Dati validi e non validi',
        'examples.validation.detail3': 'Create anomalies rende evidente il confronto; il report elenca le regole non superate.',
        'examples.validation.point4Title': 'Payload e salvataggio',
        'examples.validation.detail4': 'Le righe modificate non valide non entrano nella parte del payload pronta al salvataggio.',
        'examples.validation.point5Title': 'Correzione',
        'examples.validation.detail5': 'Correggi un valore evidenziato e valida di nuovo per rimuovere l’errore.',
        'examples.autocomplete.title': 'Autocomplete',
        'examples.autocomplete.description': 'Suggerimenti controllati per campi testuali business.',
        'examples.autocomplete.intro': 'Digita nei campi per filtrare suggerimenti e confrontare valori controllati e liberi.',
        'examples.autocomplete.detailsTitle': 'Come funziona autocomplete',
        'examples.autocomplete.guideMeta': 'Input assistito · suggerimenti',
        'examples.autocomplete.point1Title': 'Suggerimenti',
        'examples.autocomplete.detail1': 'Le opzioni compatibili compaiono e si restringono durante la digitazione.',
        'examples.autocomplete.point2Title': 'Valori strict',
        'examples.autocomplete.detail2': 'I campi Department richiedono un valore presente nella lista fornita.',
        'examples.autocomplete.point3Title': 'Valori liberi',
        'examples.autocomplete.detail3': 'Tag e city accettano anche valori personalizzati non presenti nei suggerimenti.',
        'examples.autocomplete.point4Title': 'Tastiera',
        'examples.autocomplete.detail4': 'Usa le frecce per navigare i suggerimenti e conferma senza lasciare la tastiera.',
        'examples.autocomplete.point5Title': 'Valore confermato',
        'examples.autocomplete.detail5': 'L’opzione confermata diventa il valore della cella usato da validazione e payload CRUD.',
        'examples.multifieldLookup.title': 'Multifield lookup',
        'examples.multifieldLookup.description': 'Lookup che aggiorna più campi da un record scelto.',
        'examples.multifieldLookup.intro': 'Municipality è il campo master modificabile. Digita per usare l’autocomplete oppure usa il pulsante di ricerca per aprire il lookup completo.',
        'examples.multifieldLookup.detailsTitle': 'Come funziona il multifield lookup',
        'examples.multifieldLookup.guideMeta': 'Ricerca · mapping multiplo',
        'examples.multifieldLookup.point1Title': 'Selezione record',
        'examples.multifieldLookup.detail1': 'Digita per usare l’autocomplete oppure apri il lookup completo con il pulsante di ricerca e scegli un record.',
        'examples.multifieldLookup.point2Title': 'Campo master',
        'examples.multifieldLookup.detail2': 'Comune è il campo master azionabile; i campi dipendenti restano readonly.',
        'examples.multifieldLookup.point3Title': 'Campi dipendenti',
        'examples.multifieldLookup.detail3': 'Provincia, Regione, CAP, codice ISTAT e codice catastale si aggiornano insieme.',
        'examples.multifieldLookup.point4Title': 'Ricerca',
        'examples.multifieldLookup.detail4': 'Cerca nel dataset per restringere i Comuni disponibili prima della selezione.',
        'examples.multifieldLookup.point5Title': 'Dati coerenti',
        'examples.multifieldLookup.detail5': 'La selezione di un unico record evita combinazioni incoerenti tra valori dipendenti.',
        'examples.multifieldLookup.warning': 'Avviso dati demo:',
        'examples.multifieldLookup.warningText': 'Questo dataset è fornito esclusivamente a scopo dimostrativo. Potrebbe essere incompleto, non aggiornato o inesatto. Non usarlo come fonte ufficiale in sistemi di produzione.',
        'examples.rowStates.title': 'Row states',
        'examples.rowStates.description': 'Laboratorio del lifecycle: identità, transizioni, rollback ed errori.',
        'examples.rowStates.intro': 'Come AMB Grid tiene traccia del ciclo di vita di ogni riga.',
        'examples.rowStates.detailsTitle': 'Come funzionano gli stati riga',
        'examples.rowStates.guideIntro': 'Row States mostra separatamente l’identità del record, il suo stato nel ciclo di vita e gli eventuali errori. La tabella parte pulita: puoi modificare i dati manualmente oppure usare Show states per preparare alcuni stati di esempio.',
        'examples.rowStates.guideMeta': 'Identità · transizioni · rollback',
        'examples.rowStates.point1Title': 'Identità',
        'examples.rowStates.detail1': 'ID identifica una riga persistente, Temp ID una nuova riga e il numero riga resta un riferimento stabile.',
        'examples.rowStates.point2Title': 'Transizioni',
        'examples.rowStates.detail2': 'La modifica porta clean a modified, Add crea new e Delete marca una riga persistente come deleted.',
        'examples.rowStates.point3Title': 'Rollback',
        'examples.rowStates.detail3': 'Rollback ripristina la baseline e lo stato coerente.',
        'examples.rowStates.point4Title': 'Errori',
        'examples.rowStates.detail4': 'Gli errori appartengono alla riga o alla cella e restano distinti da Deleted.',
        'examples.rowStates.point5Title': 'Salvataggio',
        'examples.rowStates.detail5': 'Save assegna gli ID definitivi, conferma le modifiche valide e rende saved osservabile nel lifecycle reale.',
        'examples.dates.title': 'Dates',
        'examples.dates.description': 'Input data, formati multipli, validazione e selezione tramite datepicker.',
        'examples.dates.intro': 'Confronta input manuale, formati data multipli, range di validazione e modalità datepicker reali.',
        'examples.dates.detailsTitle': 'Come funzionano le date',
        'examples.dates.guideMeta': 'Input · formati · datepicker',
        'examples.dates.detailsText': 'Formato, editor, visualizzazione, validazione e range restano allineati tramite configurazioni data condivise.',
        'examples.dates.point1Title': 'Formati multipli',
        'examples.dates.detail1': 'Date manuali, ISO, compatte e con trattino usano il formato dichiarato.',
        'examples.dates.point2Title': 'Manuale e datepicker',
        'examples.dates.detail2': 'Alcune celle accettano la digitazione, altre aggiungono il calendario o aprono direttamente il picker.',
        'examples.dates.point3Title': 'Validazione visibile',
        'examples.dates.detail3': 'I valori digitati non validi restano visibili per mostrare errori di sintassi, calendario o range.',
        'examples.dates.point4Title': 'Range consentito',
        'examples.dates.detail4': 'Tutte le date devono essere comprese tra 01/01/2025 e 31/12/2027.',
        'examples.dates.validate': 'Valida date',
        'examples.dates.validateTitle': 'Valida i valori data',
        'examples.parsers.title': 'Parsers',
        'examples.parsers.description': 'Normalizza i valori inseriti in formati prevedibili per il payload.',
        'examples.parsers.intro': 'Modifica un valore visuale e osserva la rappresentazione normalizzata prodotta per un payload prevedibile.',
        'examples.parsers.detailsTitle': 'Come funzionano i parser',
        'examples.parsers.guideMeta': 'Normalizzazione · payload',
        'examples.parsers.detailsText': 'I parser normalizzano valori visuali in forme orientate al backend, ma non sostituiscono validazione e regole business.',
        'examples.parsers.point1Title': 'Normalizzazione',
        'examples.parsers.detail1': 'Ogni riga applica un parser pubblico AMB al valore Input modificato.',
        'examples.parsers.point2Title': 'Forma del payload',
        'examples.parsers.detail2': 'Parsed value mostra la rappresentazione prevedibile destinata al payload applicativo.',
        'examples.parsers.point3Title': 'Validazione separata',
        'examples.parsers.detail3': 'Il parser trasforma la sintassi; validazione e regole business decidono se il dato è accettabile.',
        'examples.parsers.point4Title': 'Parser pubblici',
        'examples.parsers.detail4': "AMB Grid fornisce parser pronti all'uso per trasformazioni comuni del payload, come numeri, date, orari, booleani e valori null. Le relative opzioni possono essere configurate in base al contratto applicativo.",
        'examples.parsers.point5Title': 'Parser personalizzati',
        'examples.parsers.detail5': "Quando una regola business richiede una trasformazione specifica, AMB.parsers.custom(parseFn) permette all'applicazione di definire una propria logica di parsing riutilizzabile.",
        'examples.columnCalculations.title': 'Column calculations',
        'examples.columnCalculations.description': 'Calcoli aggregati direttamente sulle colonne: count, unique, sum, avg, min e max.',
        'examples.columnCalculations.intro': 'Modifica i valori business e osserva ogni aggregato aggiornarsi nella propria colonna.',
        'examples.columnCalculations.detailsTitle': 'Come funzionano i calcoli di colonna',
        'examples.columnCalculations.guideMeta': 'Count · sum · avg · min · max',
        'examples.columnCalculations.detailsText': 'La calculation row presenta gli aggregati accanto ai dati cui si riferiscono.',
        'examples.columnCalculations.point1Title': 'Propria colonna',
        'examples.columnCalculations.detail1': 'Ogni calcolo riceve soltanto i valori della colonna in cui viene mostrato.',
        'examples.columnCalculations.point2Title': 'Aggiornamento',
        'examples.columnCalculations.detail2': 'Modifica, aggiunta, eliminazione e rollback aggiornano gli aggregati sulle righe attive.',
        'examples.columnCalculations.point3Title': 'Riga integrata',
        'examples.columnCalculations.detail3': 'La calculation row mantiene gli aggregati nella grid senza riepiloghi manuali esterni.',
        'examples.columnCalculations.id': 'ID',
        'examples.columnCalculations.idCalc': 'COUNT conta il numero di righe.',
        'examples.columnCalculations.product': 'Prodotto',
        'examples.columnCalculations.productCalc': 'Il calcolo personalizzato conta i nomi prodotto che contengono "print".',
        'examples.columnCalculations.category': 'Categoria',
        'examples.columnCalculations.categoryCalc': 'UNIQUE conta le categorie distinte.',
        'examples.columnCalculations.quantity': 'Quantità',
        'examples.columnCalculations.quantityCalc': 'SUM somma le quantità di tutte le righe.',
        'examples.columnCalculations.unitPrice': 'Prezzo unitario',
        'examples.columnCalculations.unitPriceCalc': 'AVG calcola il prezzo unitario medio.',
        'examples.columnCalculations.deliveryDays': 'Giorni consegna',
        'examples.columnCalculations.deliveryDaysCalc': 'MIN mostra il minor numero di giorni di consegna.',
        'examples.columnCalculations.score': 'Punteggio',
        'examples.columnCalculations.scoreCalc': 'MAX mostra il punteggio più alto.'
    },
    en: {
        'examples.basicCrud.title': 'Basic CRUD',
        'examples.basicCrud.description': 'Application CRUD flow with toolbar, validation, and payload.',
        'examples.basicCrud.intro': 'Basic CRUD shows an essential data-management flow: edit, add or delete records, inspect the generated payload, and save the changes through a simulated backend response.',
        'examples.basicCrud.guideIntro': 'This example uses the lifecycle introduced in Row States in a normal CRUD flow, focusing on operations, payload, and saving. Title and Tag have simple validation rules; the following Validation example explores errors and constraints in more detail.',
        'examples.basicCrud.detailsTitle': 'How Basic CRUD works',
        'examples.basicCrud.guideMeta': '4 fields · essential CRUD',
        'examples.basicCrud.point1Title': 'Manage records',
        'examples.basicCrud.detail1': 'Edit Title, Tag or Archived, add a new note with Row, or use the row action to delete it or undo its changes.',
        'examples.basicCrud.point2Title': 'Save payload',
        'examples.basicCrud.detail2': 'Show payload displays what would be sent to the backend, separating records into inserted, updated, and deleted groups.',
        'examples.basicCrud.point3Title': 'Save',
        'examples.basicCrud.detail3': 'Save checks the pending changes and simulates the backend response. Valid changes are confirmed and new rows receive their final ID.',
        'examples.basicCrud.point4Title': 'Reset',
        'examples.basicCrud.detail4': 'Rollback restores a single row, while Reload resets the entire example to its initial data.',
        'examples.validation.title': 'Validation',
        'examples.validation.description': 'Field rules, row errors, and validation reports.',
        'examples.validation.intro': 'Validation shows built-in rules and custom validations defined by the developer. Edit the data or use Create anomalies to inspect errors, reports, and correction.',
        'examples.validation.introEmphasis': 'custom validations defined by the developer',
        'examples.validation.detailsTitle': 'How validation works',
        'examples.validation.guideMeta': 'Rules · errors · constraints',
        'examples.validation.point1Title': 'Field rules',
        'examples.validation.detail1': 'Fields demonstrate built-in validators such as required, unique, length, pattern, and format, while also supporting custom rules defined by the developer.',
        'examples.validation.detail1Emphasis': 'custom rules defined by the developer',
        'examples.validation.point2Title': 'Visible errors',
        'examples.validation.detail2': 'Leaving an invalid edited cell keeps feedback associated with that cell and row.',
        'examples.validation.point3Title': 'Valid and invalid data',
        'examples.validation.detail3': 'Create anomalies makes the contrast visible; the report lists the rules that failed.',
        'examples.validation.point4Title': 'Payload and save',
        'examples.validation.detail4': 'Invalid changed rows cannot enter the save-ready portion of the payload.',
        'examples.validation.point5Title': 'Correct and retry',
        'examples.validation.detail5': 'Correct a highlighted value and validate again to clear its error.',
        'examples.autocomplete.title': 'Autocomplete',
        'examples.autocomplete.description': 'Controlled suggestions for business text fields.',
        'examples.autocomplete.intro': 'Type in the fields to filter suggestions and compare controlled and free values.',
        'examples.autocomplete.detailsTitle': 'How autocomplete works',
        'examples.autocomplete.guideMeta': 'Assisted input · suggestions',
        'examples.autocomplete.point1Title': 'Suggestions',
        'examples.autocomplete.detail1': 'Matching options appear and narrow while you type.',
        'examples.autocomplete.point2Title': 'Strict values',
        'examples.autocomplete.detail2': 'Department fields require a value from the supplied list.',
        'examples.autocomplete.point3Title': 'Free values',
        'examples.autocomplete.detail3': 'Tag and city also accept custom values outside the suggestions.',
        'examples.autocomplete.point4Title': 'Keyboard',
        'examples.autocomplete.detail4': 'Use the arrow keys to navigate suggestions and confirm without leaving the keyboard.',
        'examples.autocomplete.point5Title': 'Committed value',
        'examples.autocomplete.detail5': 'The confirmed option becomes the cell value used by validation and the CRUD payload.',
        'examples.multifieldLookup.title': 'Multifield lookup',
        'examples.multifieldLookup.description': 'Lookup that updates several fields from one selected record.',
        'examples.multifieldLookup.intro': 'Municipality is the editable master field. Type to use autocomplete or use the search button to open the complete lookup.',
        'examples.multifieldLookup.detailsTitle': 'How multifield lookup works',
        'examples.multifieldLookup.guideMeta': 'Search · multi-field mapping',
        'examples.multifieldLookup.point1Title': 'Select a record',
        'examples.multifieldLookup.detail1': 'Type to use autocomplete or open the complete lookup with the search button and choose one record.',
        'examples.multifieldLookup.point2Title': 'Master field',
        'examples.multifieldLookup.detail2': 'Municipality is the actionable master field; dependent fields remain readonly.',
        'examples.multifieldLookup.point3Title': 'Dependent fields',
        'examples.multifieldLookup.detail3': 'Province, Region, Postal Code, ISTAT Code, and Cadastral Code update together.',
        'examples.multifieldLookup.point4Title': 'Search',
        'examples.multifieldLookup.detail4': 'Search the dataset to narrow the available municipalities before selection.',
        'examples.multifieldLookup.point5Title': 'Consistent data',
        'examples.multifieldLookup.detail5': 'Selecting one record prevents inconsistent combinations of dependent values.',
        'examples.multifieldLookup.warning': 'Demo data warning:',
        'examples.multifieldLookup.warningText': 'This dataset is provided for demonstration purposes only. It may be incomplete, outdated, or inaccurate. Do not use it as an official source for production systems.',
        'examples.rowStates.title': 'Row states',
        'examples.rowStates.description': 'Lifecycle laboratory: identity, transitions, rollback, and errors.',
        'examples.rowStates.intro': 'How AMB Grid tracks each row through its lifecycle.',
        'examples.rowStates.detailsTitle': 'How row states work',
        'examples.rowStates.guideIntro': 'Row States keeps record identity, lifecycle state, and errors separate. The table starts clean: edit manually or use Show states to prepare example states.',
        'examples.rowStates.guideMeta': 'Identity · transitions · rollback',
        'examples.rowStates.point1Title': 'Identity',
        'examples.rowStates.detail1': 'ID identifies a persisted row, Temp ID identifies an unsaved row, and row number remains a stable reference.',
        'examples.rowStates.point2Title': 'Transitions',
        'examples.rowStates.detail2': 'Editing moves clean to modified, Add creates new, and Delete marks a persisted row deleted.',
        'examples.rowStates.point3Title': 'Rollback',
        'examples.rowStates.detail3': 'Rollback restores the baseline and its matching state.',
        'examples.rowStates.point4Title': 'Errors',
        'examples.rowStates.detail4': 'Errors belong to a row or cell and remain distinct from Deleted.',
        'examples.rowStates.point5Title': 'Save',
        'examples.rowStates.detail5': 'Save assigns definitive IDs, confirms valid changes, and exposes saved through the real lifecycle.',
        'examples.dates.title': 'Dates',
        'examples.dates.description': 'Date input, multiple formats, validation and datepicker selection.',
        'examples.dates.intro': 'Compare manual date input, multiple formats, validation ranges, and real datepicker modes.',
        'examples.dates.detailsTitle': 'How dates work',
        'examples.dates.guideMeta': 'Input · formats · datepicker',
        'examples.dates.detailsText': 'Date format, editor behavior, display, validation, and range constraints stay aligned through shared date configurations.',
        'examples.dates.point1Title': 'Multiple formats',
        'examples.dates.detail1': 'Manual, ISO-style, compact, and dash-separated dates use their declared formats.',
        'examples.dates.point2Title': 'Manual and picker',
        'examples.dates.detail2': 'Some cells accept typing, some add a calendar button, and picker-only opens the calendar directly.',
        'examples.dates.point3Title': 'Visible validation',
        'examples.dates.detail3': 'Invalid typed values remain visible so validation can explain syntax, calendar, or range errors.',
        'examples.dates.point4Title': 'Allowed range',
        'examples.dates.detail4': 'Every date stays between 01/01/2025 and 31/12/2027.',
        'examples.dates.validate': 'Validate dates',
        'examples.dates.validateTitle': 'Validate date values',
        'examples.parsers.title': 'Parsers',
        'examples.parsers.description': 'Normalize edited values into predictable payload formats.',
        'examples.parsers.intro': 'Edit an input value and inspect the normalized representation produced for a predictable payload.',
        'examples.parsers.detailsTitle': 'How parsers work',
        'examples.parsers.guideMeta': 'Normalization · payload',
        'examples.parsers.detailsText': 'Parsers normalize visual values into backend-oriented shapes, but they do not replace validation or business rules.',
        'examples.parsers.point1Title': 'Normalization',
        'examples.parsers.detail1': 'Each row applies one public AMB parser to the edited Input value.',
        'examples.parsers.point2Title': 'Payload shape',
        'examples.parsers.detail2': 'Parsed value shows the predictable representation intended for application payloads.',
        'examples.parsers.point3Title': 'Separate validation',
        'examples.parsers.detail3': 'A parser transforms syntax; validation and business rules still decide whether data is acceptable.',
        'examples.parsers.point4Title': 'Built-in parsers',
        'examples.parsers.detail4': 'AMB Grid provides ready-to-use parsers for common payload transformations such as numbers, dates, times, booleans and null values. Their options can be configured for the application contract.',
        'examples.parsers.point5Title': 'Custom parsers',
        'examples.parsers.detail5': 'When a business rule needs a specific transformation, AMB.parsers.custom(parseFn) lets the application define its own reusable parsing logic.',
        'examples.columnCalculations.title': 'Column calculations',
        'examples.columnCalculations.description': 'Aggregate column calculations for count, unique, sum, avg, min, and max.',
        'examples.columnCalculations.intro': 'Edit the business values and see each aggregate update in its own column.',
        'examples.columnCalculations.detailsTitle': 'How column calculations work',
        'examples.columnCalculations.guideMeta': 'Count · sum · avg · min · max',
        'examples.columnCalculations.detailsText': 'The calculation row presents aggregates next to the data they describe.',
        'examples.columnCalculations.point1Title': 'Own column',
        'examples.columnCalculations.detail1': 'Every calculation receives only the values from the column where it is displayed.',
        'examples.columnCalculations.point2Title': 'Live updates',
        'examples.columnCalculations.detail2': 'Edit, add, delete, or undo and the corresponding aggregates follow the active rows.',
        'examples.columnCalculations.point3Title': 'Built-in row',
        'examples.columnCalculations.detail3': 'The calculation row keeps aggregates in the grid without external manual summaries.',
        'examples.columnCalculations.id': 'ID',
        'examples.columnCalculations.idCalc': 'COUNT returns the number of rows.',
        'examples.columnCalculations.product': 'Product',
        'examples.columnCalculations.productCalc': 'The custom calculation counts product names containing "print".',
        'examples.columnCalculations.category': 'Category',
        'examples.columnCalculations.categoryCalc': 'UNIQUE counts the distinct categories.',
        'examples.columnCalculations.quantity': 'Quantity',
        'examples.columnCalculations.quantityCalc': 'SUM adds all quantities.',
        'examples.columnCalculations.unitPrice': 'Unit price',
        'examples.columnCalculations.unitPriceCalc': 'AVG calculates the average unit price.',
        'examples.columnCalculations.deliveryDays': 'Delivery days',
        'examples.columnCalculations.deliveryDaysCalc': 'MIN returns the shortest delivery time.',
        'examples.columnCalculations.score': 'Score',
        'examples.columnCalculations.scoreCalc': 'MAX returns the highest score.'
    }
};
