export const publicExampleTranslations = {
    it: {
        'examples.basicCrud.title': 'Basic CRUD',
        'examples.basicCrud.description': 'CRUD minimo con toolbar e payload applicativo.',
        'examples.basicCrud.intro': 'Modifica le righe, aggiungi record, marca elementi per l’eliminazione e osserva il payload di salvataggio generato da AMB Grid.',
        'examples.basicCrud.detailsTitle': 'Come funziona Basic CRUD',
        'examples.basicCrud.detail1': 'Add Row crea una nuova riga lato client e la modifica di una cella marca la riga come modified.',
        'examples.basicCrud.detail2': 'Delete marca le righe esistenti per l’eliminazione e rimuove quelle nuove non ancora salvate.',
        'examples.basicCrud.detail3': 'Save valida le modifiche, costruisce il payload e simula la conferma del backend.',
        'examples.validation.title': 'Validation',
        'examples.validation.description': 'Regole campo, errori riga e report di validazione.',
        'examples.validation.intro': 'Le validazioni principali vengono eseguite quando lasci una cella modificata. La toolbar consente di creare errori intenzionali, aprire il report o ripristinare i dati.',
        'examples.validation.detailsTitle': 'Regole e limiti della validazione',
        'examples.validation.detail1': 'Alias ed email mostrano regole required, unique, lunghezza e formato.',
        'examples.validation.detail2': 'Codice Fiscale, Partita IVA, IBAN e documento usano controlli sintattici dimostrativi.',
        'examples.validation.detail3': 'Le verifiche del frontend non sostituiscono validazione backend, autorizzazione o regole business.',
        'examples.autocomplete.title': 'Autocomplete',
        'examples.autocomplete.description': 'Suggerimenti controllati per campi testuali business.',
        'examples.autocomplete.intro': 'Autocomplete aiuta a scegliere valori suggeriti mentre AMB Grid mantiene il controllo su commit, validazione e stato riga.',
        'examples.autocomplete.detailsTitle': 'Come funziona autocomplete',
        'examples.autocomplete.detail1': 'La modalità strict richiede un valore suggerito; la modalità free accetta valori personalizzati.',
        'examples.autocomplete.detail2': 'I suggerimenti vengono filtrati durante la digitazione e sono selezionabili da tastiera.',
        'examples.autocomplete.detail3': 'I valori strict sconosciuti restano visibili e vengono segnalati dalla validazione.',
        'examples.multifieldLookup.title': 'Multifield lookup',
        'examples.multifieldLookup.description': 'Lookup che aggiorna più campi da un record scelto.',
        'examples.multifieldLookup.intro': 'Apri il lookup dalla cella Comune: la selezione mantiene sincronizzati Comune, Provincia, Regione, CAP, codice ISTAT e codice catastale.',
        'examples.multifieldLookup.detailsTitle': 'Come funziona il multifield lookup',
        'examples.multifieldLookup.detail1': 'La cella Comune apre il lookup e la selezione completa tutti i campi collegati.',
        'examples.multifieldLookup.detail2': 'Le celle derivate sono readonly e non vengono modificate direttamente.',
        'examples.multifieldLookup.detail3': 'Il payload include i dati CRUD pronti per l’integrazione backend.',
        'examples.multifieldLookup.warning': 'Avviso dati demo:',
        'examples.multifieldLookup.warningText': 'Questo dataset è fornito esclusivamente a scopo dimostrativo. Potrebbe essere incompleto, non aggiornato o inesatto. Non usarlo come fonte ufficiale in sistemi di produzione.',
        'examples.rowStates.title': 'Row states',
        'examples.rowStates.description': 'Stati riga, rollback, delete e report tecnici.',
        'examples.rowStates.intro': 'Usa la toolbar CRUD e la colonna delete per esplorare come AMB Grid segue ogni riga nel suo ciclo di vita.',
        'examples.rowStates.detailsTitle': 'Come funzionano gli stati riga',
        'examples.rowStates.detail1': 'clean, new, modified, deleted e saved sono gli stati del ciclo di vita.',
        'examples.rowStates.detail2': 'Gli errori sono indicatori separati e non costituiscono uno stato del ciclo di vita.',
        'examples.rowStates.detail3': 'Save agisce soltanto sulle righe valide new, modified o deleted; Reload ripristina dati e stati iniziali.',
        'examples.rowStates.detail4': '_ambTempId, _ambRowNumber e _state sono mostrati esclusivamente a scopo dimostrativo.',
        'examples.columnCalculations.title': 'Column calculations',
        'examples.columnCalculations.description': 'Calcoli aggregati direttamente sulle colonne: count, unique, sum, avg, min e max.',
        'examples.columnCalculations.intro': 'Modifica i valori business e osserva ogni aggregato aggiornarsi nella propria colonna.',
        'examples.columnCalculations.detailsTitle': 'Come funzionano i calcoli di colonna',
        'examples.columnCalculations.detailsText': 'AMB Grid mostra i valori aggregati nella riga di calcolo. Ogni risultato usa i valori della propria colonna e si aggiorna quando i dati cambiano.',
        'examples.columnCalculations.category': 'Categoria',
        'examples.columnCalculations.quantity': 'Quantità',
        'examples.columnCalculations.unitPrice': 'Prezzo unitario',
        'examples.columnCalculations.deliveryDays': 'Giorni consegna',
        'examples.columnCalculations.score': 'Punteggio'
    },
    en: {
        'examples.basicCrud.title': 'Basic CRUD',
        'examples.basicCrud.description': 'Minimal CRUD with toolbar and application payload.',
        'examples.basicCrud.intro': 'Edit rows, add records, mark items for deletion, and inspect the save payload generated by AMB Grid.',
        'examples.basicCrud.detailsTitle': 'Basic CRUD behavior',
        'examples.basicCrud.detail1': 'Add Row creates a client-side row, while editing a cell marks its row as modified.',
        'examples.basicCrud.detail2': 'Delete marks existing rows for deletion and removes unsaved new rows.',
        'examples.basicCrud.detail3': 'Save validates changes, builds the payload, and simulates backend confirmation.',
        'examples.validation.title': 'Validation',
        'examples.validation.description': 'Field rules, row errors, and validation reports.',
        'examples.validation.intro': 'Most validations run when you leave an edited cell. The toolbar can create intentional errors, open the report, or reset the data.',
        'examples.validation.detailsTitle': 'Validation rules and limits',
        'examples.validation.detail1': 'Alias and email demonstrate required, unique, length, and format rules.',
        'examples.validation.detail2': 'Fiscal code, VAT number, IBAN, and document fields use demonstrative syntax checks.',
        'examples.validation.detail3': 'Frontend checks do not replace backend validation, authorization, or business rules.',
        'examples.autocomplete.title': 'Autocomplete',
        'examples.autocomplete.description': 'Controlled suggestions for business text fields.',
        'examples.autocomplete.intro': 'Autocomplete helps users choose suggested values while AMB Grid controls commit, validation, and row state.',
        'examples.autocomplete.detailsTitle': 'Autocomplete behavior',
        'examples.autocomplete.detail1': 'Strict mode requires a suggested value; free mode accepts custom values.',
        'examples.autocomplete.detail2': 'Suggestions are filtered while typing and can be selected with the keyboard.',
        'examples.autocomplete.detail3': 'Unknown strict values remain visible and are reported by validation.',
        'examples.multifieldLookup.title': 'Multifield lookup',
        'examples.multifieldLookup.description': 'Lookup that updates several fields from one selected record.',
        'examples.multifieldLookup.intro': 'Open the lookup from the Municipality cell: selection keeps Municipality, Province, Region, Postal Code, ISTAT Code, and Cadastral Code synchronized.',
        'examples.multifieldLookup.detailsTitle': 'Multifield lookup behavior',
        'examples.multifieldLookup.detail1': 'The Municipality cell opens the lookup and selection fills every connected field.',
        'examples.multifieldLookup.detail2': 'Derived cells are readonly and are not edited directly.',
        'examples.multifieldLookup.detail3': 'The payload includes CRUD data ready for backend integration.',
        'examples.multifieldLookup.warning': 'Demo data warning:',
        'examples.multifieldLookup.warningText': 'This dataset is provided for demonstration purposes only. It may be incomplete, outdated, or inaccurate. Do not use it as an official source for production systems.',
        'examples.rowStates.title': 'Row states',
        'examples.rowStates.description': 'Row states, rollback, delete, and technical reports.',
        'examples.rowStates.intro': 'Use the CRUD toolbar and delete column to explore how AMB Grid tracks each row through its lifecycle.',
        'examples.rowStates.detailsTitle': 'Row states behavior',
        'examples.rowStates.detail1': 'clean, new, modified, deleted, and saved are lifecycle states.',
        'examples.rowStates.detail2': 'Errors are separate indicators and are not lifecycle states.',
        'examples.rowStates.detail3': 'Save acts only on valid new, modified, or deleted rows; Reload restores the initial data and states.',
        'examples.rowStates.detail4': '_ambTempId, _ambRowNumber, and _state are exposed for demonstration only.',
        'examples.columnCalculations.title': 'Column calculations',
        'examples.columnCalculations.description': 'Aggregate column calculations for count, unique, sum, avg, min, and max.',
        'examples.columnCalculations.intro': 'Edit the business values and see each aggregate update in its own column.',
        'examples.columnCalculations.detailsTitle': 'How column calculations work',
        'examples.columnCalculations.detailsText': 'AMB Grid displays aggregate values in the calculation row. Each result uses its own column values and updates when the data changes.',
        'examples.columnCalculations.category': 'Category',
        'examples.columnCalculations.quantity': 'Quantity',
        'examples.columnCalculations.unitPrice': 'Unit price',
        'examples.columnCalculations.deliveryDays': 'Delivery days',
        'examples.columnCalculations.score': 'Score'
    }
};
