import { AMB } from '../index.js';
import {
    MUNICIPALITY_LOOKUP_COLUMNS,
    MUNICIPALITY_MAP_TO_ROW
} from './multifield-lookup-config.js';
import { createDemoReportDialog } from './utils/demo-report-dialog.js';
import { createDemoColumnGuide } from './utils/demo-column-guide.js';

const DATASET_URL = new URL('./data/italian-municipalities.demo.json', import.meta.url);
const DATASET_WARNING = 'This dataset is provided for demonstration purposes only. '
    + 'It may be incomplete, outdated, or inaccurate. '
    + 'Do not use it as an official source for production systems.';

const filterMunicipalities = (records, query) => {
    const normalizedQuery = String(query || '').trim().toLowerCase();

    if (!normalizedQuery) return records;

    return records.filter(record => {
        return [
            record.municipalityName,
            record.province,
            record.region,
            record.postalCode,
            record.istatCode,
            record.cadastralCode
        ].some(value => {
            return String(value || '').toLowerCase().includes(normalizedQuery);
        });
    });
};
const createInitialData = () => [
    {
        id: 1,
        istatCode: '065078',
        cadastralCode: 'F912',
        municipality: 'Nocera Inferiore',
        province: 'SA',
        region: 'CAMPANIA',
        postalCode: '84014'
    },
    {
        id: 2,
        istatCode: '015146',
        cadastralCode: 'F205',
        municipality: 'Milano',
        province: 'MI',
        region: 'LOMBARDIA',
        postalCode: '20121'
    },
    {
        id: 3,
        istatCode: '048017',
        cadastralCode: 'D612',
        municipality: 'Firenze',
        province: 'FI',
        region: 'TOSCANA',
        postalCode: '50121'
    },
    {
        id: 4,
        istatCode: '082053',
        cadastralCode: 'G273',
        municipality: 'Palermo',
        province: 'PA',
        region: 'SICILIA',
        postalCode: '90121'
    },
    {
        id: 5,
        istatCode: '058091',
        cadastralCode: 'H501',
        municipality: 'Roma',
        province: 'RM',
        region: 'LAZIO',
        postalCode: '00118'
    },
    {
        id: 6,
        istatCode: '001272',
        cadastralCode: 'L219',
        municipality: 'Torino',
        province: 'TO',
        region: 'PIEMONTE',
        postalCode: '10121'
    },
    {
        id: 7,
        istatCode: '037006',
        cadastralCode: 'A944',
        municipality: 'Bologna',
        province: 'BO',
        region: 'EMILIA-ROMAGNA',
        postalCode: '40121'
    },
    {
        id: 8,
        istatCode: '063049',
        cadastralCode: 'F839',
        municipality: 'Napoli',
        province: 'NA',
        region: 'CAMPANIA',
        postalCode: '80121'
    },
    {
        id: 9,
        istatCode: '010025',
        cadastralCode: 'D969',
        municipality: 'Genova',
        province: 'GE',
        region: 'LIGURIA',
        postalCode: '16121'
    },
    {
        id: 10,
        istatCode: '027042',
        cadastralCode: 'L736',
        municipality: 'Venezia',
        province: 'VE',
        region: 'VENETO',
        postalCode: '30121'
    }
];

const createEmptyMunicipalityRow = () => ({
    id: null,
    istatCode: '',
    cadastralCode: '',
    municipality: '',
    province: '',
    region: '',
    postalCode: ''
});

const buildPayloadReport = payload => {
    const inserted = payload.changes.inserted.length;
    const updated = payload.changes.updated.length;
    const deleted = payload.changes.deleted.length;

    return [
        'Multifield lookup payload',
        '',
        `Rows ready for save: ${inserted + updated + deleted}`,
        `Inserted rows: ${inserted}`,
        `Updated rows: ${updated}`,
        `Deleted rows: ${deleted}`,
        '',
        'The JSON tab shows the backend-ready CRUD payload generated by AMB Grid.'
    ];
};

const loadMunicipalities = async () => {
    const response = await fetch(DATASET_URL);

    if (!response.ok) {
        throw new Error(`Unable to load the municipality demo dataset (${response.status})`);
    }

    return response.json();
};

export default async function multifieldLookup(app) {
    app.innerHTML = `
        <div class="demo-multifield-lookup">
            <h2 data-i18n="examples.multifieldLookup.title">Multifield lookup</h2>
            <p class="demo-note" data-i18n="examples.multifieldLookup.intro">Municipality is the editable master field. Type to use autocomplete or use the search button to open the complete lookup.</p>
            ${createDemoColumnGuide({
            summary: 'Multifield lookup behavior',
            summaryKey: 'examples.multifieldLookup.detailsTitle',
            points: [
                { title: 'Select a record', titleKey: 'examples.multifieldLookup.point1Title', description: 'Click Municipality and choose one complete record from the lookup.', descriptionKey: 'examples.multifieldLookup.detail1' },
                { title: 'Master field', titleKey: 'examples.multifieldLookup.point2Title', description: 'Municipality is the actionable master field; dependent fields remain readonly.', descriptionKey: 'examples.multifieldLookup.detail2' },
                { title: 'Dependent fields', titleKey: 'examples.multifieldLookup.point3Title', description: 'Province, Region, Postal Code, ISTAT Code, and Cadastral Code update together.', descriptionKey: 'examples.multifieldLookup.detail3' },
                { title: 'Search', titleKey: 'examples.multifieldLookup.point4Title', description: 'Search the lookup dataset to narrow the available municipalities before selection.', descriptionKey: 'examples.multifieldLookup.detail4' },
                { title: 'Consistent data', titleKey: 'examples.multifieldLookup.point5Title', description: 'Selecting one record prevents combinations of dependent values that do not belong together.', descriptionKey: 'examples.multifieldLookup.detail5' }
            ],
            columns: [
                { title: 'Municipality', titleKey: 'guides.multifield.municipality.title', badge: 'MASTER', description: 'Editable master field: type for autocomplete or use the search button to open the complete lookup.', descriptionKey: 'guides.multifield.municipality.description' },
                { title: 'Province', titleKey: 'guides.multifield.province.title', badge: 'DERIVED', description: 'Readonly value filled automatically from the selected municipality.', descriptionKey: 'guides.multifield.province.description' },
                { title: 'Region', titleKey: 'guides.multifield.region.title', badge: 'DERIVED', description: 'Readonly region synchronized with the master selection.', descriptionKey: 'guides.multifield.region.description' },
                { title: 'Postal Code', titleKey: 'guides.multifield.postalCode.title', badge: 'DERIVED', description: 'Readonly postal code supplied by the selected record.', descriptionKey: 'guides.multifield.postalCode.description' },
                { title: 'ISTAT Code', titleKey: 'guides.multifield.istatCode.title', badge: 'DERIVED', description: 'Readonly ISTAT identifier supplied by the selected record.', descriptionKey: 'guides.multifield.istatCode.description' },
                { title: 'Cadastral Code', titleKey: 'guides.multifield.cadastralCode.title', badge: 'DERIVED', description: 'Derived field, hidden in the lookup and filled after selection.', descriptionKey: 'guides.multifield.cadastralCode.description' }
            ]
            })}
            <p class="demo-warning"><strong data-i18n="examples.multifieldLookup.warning">Demo data warning:</strong> <span data-i18n="examples.multifieldLookup.warningText">${DATASET_WARNING}</span></p>
            <div class="demo-table-workbench">
                <div id="municipality-table" class="demo-business-grid demo-business-grid--viewport"></div>
            </div>
        </div>
    `;

    const tableMount = app.querySelector('#municipality-table');
    let municipalities;

    try {
        municipalities = await loadMunicipalities();
    } catch (error) {
        tableMount.textContent = error.message;
        return null;
    }

    const municipalityLookup = AMB.lookup({
        keyField: 'istatCode',
        valueField: 'municipalityName',
        labelField: 'municipalityName',
        columns: MUNICIPALITY_LOOKUP_COLUMNS,
        search: {
            fields: 'visible'
        },
        mapToRow: MUNICIPALITY_MAP_TO_ROW,
        load: ({ query }) => filterMunicipalities(municipalities, query)
    });
    const municipalityDialog = new AMB.LookupDialog();
    const municipalityMultifieldLookup = AMB.multifieldLookup({
        id: 'municipality',
        lookup: municipalityLookup,
        masterField: {
            field: 'municipality',
            from: 'municipalityName',
            title: 'Municipality',
            required: true,
            autocomplete: true,
            dialog: true
        },
        dependentFields: [
            {
                field: 'province',
                from: 'province',
                title: 'Province',
                visibleInGrid: true,
                visibleInLookup: true,
                searchable: true,
                required: true
            },
            {
                field: 'region',
                from: 'region',
                title: 'Region',
                visibleInGrid: true,
                visibleInLookup: true,
                searchable: true,
                required: true
            },
            {
                field: 'postalCode',
                from: 'postalCode',
                title: 'Postal Code',
                visibleInGrid: true,
                visibleInLookup: true,
                searchable: true,
                required: true
            },
            {
                field: 'istatCode',
                from: 'istatCode',
                title: 'ISTAT Code',
                visibleInGrid: true,
                visibleInLookup: false,
                searchable: false,
                required: true
            },
            {
                field: 'cadastralCode',
                from: 'cadastralCode',
                title: 'Cadastral Code',
                visibleInGrid: true,
                visibleInLookup: false,
                searchable: false,
                required: true
            }
        ]
    });
    let grid = null;
    const reportDialog = createDemoReportDialog();

    grid = AMB.table({
        selector: '#municipality-table',
        data: createInitialData(),
        toolbar: {
            buttons: [
                'add',
                'payload',
                {
                    id: 'reset-data',
                    label: 'Reset data',
                    title: 'Reset municipality demo data',
                    onClick: handleResetData
                }
            ],
            onAdd: handleAddRow,
            onPayload: handleShowPayload
        },
        layout: 'fitColumns',
        deleteColumn: {
            enabled: true
        },
        columns: [
            municipalityMultifieldLookup.masterColumn({
                minWidth: 165,
                widthGrow: 1.7,
                dialog: municipalityDialog,
                editorOptions: {
                    dialogTitle: 'Select an Italian municipality',
                    searchPlaceholder: 'Search municipality, province, region, or postal code...',
                    autoComplete: true,
                    autoCompleteMinChars: 1,
                    autoCompleteOnTab: true,
                    dialogOptions: {
                        closeOnBackdropClick: false,
                        pagination: {
                            enabled: true,
                            pageSize: 100,
                            controls: 'full'
                        },
                        destroyOnClose: true
                    }
                }
            }),
            municipalityMultifieldLookup.dependentColumn('province', {
                minWidth: 88,
                widthGrow: 0.65
            }),
            municipalityMultifieldLookup.dependentColumn('region', {
                minWidth: 105,
                widthGrow: 1
            }),
            municipalityMultifieldLookup.dependentColumn('postalCode', {
                minWidth: 105,
                widthGrow: 0.8
            }),
            municipalityMultifieldLookup.dependentColumn('istatCode', {
                minWidth: 105,
                widthGrow: 0.8
            }),
            municipalityMultifieldLookup.dependentColumn('cadastralCode', {
                minWidth: 125,
                widthGrow: 0.95
            })
        ]
    });

    function handleAddRow() {
        grid.feedback.clear();
        return grid.crud.addRow(createEmptyMunicipalityRow());
    }

    async function handleResetData() {
        grid.feedback.clear();
        await grid.table.setData(createInitialData());
        grid.feedback.show({
            type: 'success',
            message: 'Municipality demo data reset.'
        });
    }

    function handleShowPayload({ payload }) {
        reportDialog.open({
            title: 'Multifield lookup payload',
            reportLines: buildPayloadReport(payload),
            jsonData: payload
        });
    }

    return {
        ...grid,
        destroy() {
            reportDialog.destroy();

            municipalityDialog.destroy();

            grid.destroy();
        }
    };
}
