import { AMB } from '../index.js';
import {
    applyMunicipalitySelection,
    MUNICIPALITY_LOOKUP_COLUMNS,
    MUNICIPALITY_MAP_TO_ROW
} from './multifield-lookup-config.js';
import { createDemoReportDialog } from './utils/demo-report-dialog.js';

const DATASET_URL = `${import.meta.env.BASE_URL}demo/data/italian-municipalities.demo.json`;
const DATASET_WARNING = 'This dataset is provided for demonstration purposes only. '
    + 'It may be incomplete, outdated, or inaccurate. '
    + 'Do not use it as an official source for production systems.';
const LOOKUP_OPEN_DELAY = 150;
const createInitialData = () => [
    {
        id: 1,
        istatCode: '065078',
        cadastralCode: 'F912',
        municipality: 'Nocera Inferiore',
        province: 'SA',
        region: 'CAMPANIA',
        postalCode: '84014'
    },
    {
        id: 2,
        istatCode: '015146',
        cadastralCode: 'F205',
        municipality: 'Milano',
        province: 'MI',
        region: 'LOMBARDIA',
        postalCode: '20121'
    },
    {
        id: 3,
        istatCode: '048017',
        cadastralCode: 'D612',
        municipality: 'Firenze',
        province: 'FI',
        region: 'TOSCANA',
        postalCode: '50121'
    },
    {
        id: 4,
        istatCode: '082053',
        cadastralCode: 'G273',
        municipality: 'Palermo',
        province: 'PA',
        region: 'SICILIA',
        postalCode: '90121'
    }
];

const createEmptyMunicipalityRow = () => ({
    id: null,
    istatCode: '',
    cadastralCode: '',
    municipality: '',
    province: '',
    region: '',
    postalCode: ''
});

const buildPayloadReport = payload => {
    const inserted = payload.changes.inserted.length;
    const updated = payload.changes.updated.length;
    const deleted = payload.changes.deleted.length;

    return [
        'Multifield lookup payload',
        '',
        `Rows ready for save: ${inserted + updated + deleted}`,
        `Inserted rows: ${inserted}`,
        `Updated rows: ${updated}`,
        `Deleted rows: ${deleted}`,
        '',
        'The JSON tab shows the backend-ready CRUD payload generated by AMB Grid.'
    ];
};

const restoreLookupOriginFocus = cell => {
    globalThis.requestAnimationFrame(() => {
        const element = cell && cell.getElement && cell.getElement();

        if (!element || typeof element.focus !== 'function') return;

        try {
            element.focus({ preventScroll: true });
        } catch {
            element.focus();
        }
    });
};

const loadMunicipalities = async () => {
    const response = await fetch(DATASET_URL);

    if (!response.ok) {
        throw new Error(`Unable to load the municipality demo dataset (${response.status})`);
    }

    return response.json();
};

export default async function multifieldLookup(app) {
    app.innerHTML = `
        <h2 data-i18n="examples.multifieldLookup.title">Multifield lookup</h2>
        <p class="demo-note" data-i18n="examples.multifieldLookup.intro">Open the lookup from the Municipality cell: selection keeps Municipality, Province, Region, Postal Code, ISTAT Code, and Cadastral Code synchronized.</p>
        <details class="demo-disclosure">
            <summary class="demo-disclosure__summary" data-i18n="examples.multifieldLookup.detailsTitle">Multifield lookup behavior</summary>
            <div class="demo-disclosure__content">
                <ul class="demo-explanation-list">
                    <li><strong data-i18n="examples.multifieldLookup.point1Title">Select a record</strong><span data-i18n="examples.multifieldLookup.detail1">Click Municipality and choose one complete record from the lookup.</span></li>
                    <li><strong data-i18n="examples.multifieldLookup.point2Title">Master field</strong><span data-i18n="examples.multifieldLookup.detail2">Municipality is the actionable master field; dependent fields remain readonly.</span></li>
                    <li><strong data-i18n="examples.multifieldLookup.point3Title">Dependent fields</strong><span data-i18n="examples.multifieldLookup.detail3">Province, Region, Postal Code, ISTAT Code, and Cadastral Code update together.</span></li>
                    <li><strong data-i18n="examples.multifieldLookup.point4Title">Search</strong><span data-i18n="examples.multifieldLookup.detail4">Search the lookup dataset to narrow the available municipalities before selection.</span></li>
                    <li><strong data-i18n="examples.multifieldLookup.point5Title">Consistent data</strong><span data-i18n="examples.multifieldLookup.detail5">Selecting one record prevents combinations of dependent values that do not belong together.</span></li>
                </ul>
            </div>
        </details>
        <p class="demo-warning"><strong data-i18n="examples.multifieldLookup.warning">Demo data warning:</strong> <span data-i18n="examples.multifieldLookup.warningText">${DATASET_WARNING}</span></p>
        <div id="municipality-table" class="demo-example-grid-frame"></div>
    `;

    const tableMount = app.querySelector('#municipality-table');
    let municipalities;

    try {
        municipalities = await loadMunicipalities();
    } catch (error) {
        tableMount.textContent = error.message;
        return null;
    }

    const municipalityLookup = AMB.lookup({
        keyField: 'istatCode',
        valueField: 'istatCode',
        labelField: 'municipalityName',
        columns: MUNICIPALITY_LOOKUP_COLUMNS,
        search: {
            fields: 'visible'
        },
        mapToRow: MUNICIPALITY_MAP_TO_ROW,
        load: () => municipalities
    });
    const lookupDialog = new AMB.LookupDialog();
    let grid = null;
    let pendingLookupTimer = null;
    let pendingLookupCell = null;
    let pendingLookupRow = null;
    let activeLookupRow = null;
    let destroyed = false;
    const reportDialog = createDemoReportDialog();

    const openMunicipalityLookup = async cell => {
        if (!grid || destroyed) return;

        const row = cell.getRow();
        const rowData = row.getData();
        const stateField = grid.crud.options.stateField;

        if (rowData[stateField] === 'deleted') return;

        const visibleColumns = municipalityLookup.columns.filter(column => {
            return column.visible === true;
        });
        const selected = await lookupDialog.open({
            title: 'Select an Italian municipality',
            columns: visibleColumns,
            data: await municipalityLookup.load(),
            closeOnBackdropClick: false,
            pagination: {
                enabled: true,
                pageSize: 100,
                controls: 'full'
            },
            valueField: municipalityLookup.keyField,
            searchFields: visibleColumns.map(column => column.field),
            searchPlaceholder: 'Search municipality, province, region, or postal code...'
        });

        if (destroyed) return;

        const applied = applyMunicipalitySelection({
            selected,
            rowData,
            crud: grid.crud
        });

        if (applied) {
            restoreLookupOriginFocus(cell);
        }
    };

    const scheduleMunicipalityLookup = cell => {
        if (!grid || destroyed || pendingLookupTimer || activeLookupRow) return;

        const row = cell.getRow();
        const rowData = row.getData();

        if (rowData[grid.crud.options.stateField] === 'deleted') return;

        // Set the pending guard before the delay so a second click from a
        // double-click cannot schedule or interact with another dialog.
        pendingLookupCell = cell;
        pendingLookupRow = row;
        pendingLookupTimer = globalThis.setTimeout(async () => {
            const scheduledCell = pendingLookupCell;

            pendingLookupTimer = null;
            pendingLookupCell = null;
            activeLookupRow = pendingLookupRow;
            pendingLookupRow = null;

            if (destroyed || !scheduledCell) {
                activeLookupRow = null;
                return;
            }

            try {
                await openMunicipalityLookup(scheduledCell);
            } finally {
                activeLookupRow = null;
            }
        }, LOOKUP_OPEN_DELAY);
    };

    grid = AMB.table({
        selector: '#municipality-table',
        data: createInitialData(),
        toolbar: {
            buttons: [
                'add',
                'payload',
                {
                    id: 'reset-data',
                    label: 'Reset data',
                    title: 'Reset municipality demo data',
                    onClick: handleResetData
                }
            ],
            onAdd: handleAddRow,
            onPayload: handleShowPayload
        },
        layout: 'fitColumns',
        deleteColumn: {
            enabled: true
        },
        columns: [
            {
                title: 'Municipality',
                field: 'municipality',
                minWidth: 165,
                widthGrow: 1.7,
                required: true,
                editable: false,
                cssClass: 'amb-cell--readonly-actionable amb-cell--actionable',
                cellClick: (event, cell) => {
                    event.preventDefault?.();
                    scheduleMunicipalityLookup(cell);
                },
                cellDblClick: event => {
                    event.preventDefault?.();
                    event.stopPropagation?.();
                }
            },
            {
                title: 'Province',
                field: 'province',
                required: true,
                minWidth: 88,
                widthGrow: 0.65,
                editable: false,
                cssClass: 'amb-cell--readonly-passive amb-cell--derived'
            },
            {
                title: 'Region',
                field: 'region',
                minWidth: 105,
                widthGrow: 1,
                editable: false,
                cssClass: 'amb-cell--readonly-passive amb-cell--derived'
            },
            {
                title: 'Postal Code',
                field: 'postalCode',
                minWidth: 105,
                widthGrow: 0.8,
                editable: false,
                cssClass: 'amb-cell--readonly-passive amb-cell--derived'
            },
            {
                title: 'ISTAT Code',
                field: 'istatCode',
                minWidth: 105,
                widthGrow: 0.8,
                editable: false,
                cssClass: 'amb-cell--readonly-passive amb-cell--derived'
            },
            {
                title: 'Cadastral Code',
                field: 'cadastralCode',
                minWidth: 125,
                widthGrow: 0.95,
                editable: false,
                cssClass: 'amb-cell--readonly-passive amb-cell--derived'
            }
        ]
    });

    function handleAddRow() {
        grid.feedback.clear();
        return grid.crud.addRow(createEmptyMunicipalityRow());
    }

    async function handleResetData() {
        grid.feedback.clear();
        await grid.table.setData(createInitialData());
        grid.feedback.show({
            type: 'success',
            message: 'Municipality demo data reset.'
        });
    }

    function handleShowPayload({ payload }) {
        reportDialog.open({
            title: 'Multifield lookup payload',
            reportLines: buildPayloadReport(payload),
            jsonData: payload
        });
    }

    return {
        ...grid,
        destroy() {
            destroyed = true;
            reportDialog.destroy();

            if (pendingLookupTimer) {
                globalThis.clearTimeout(pendingLookupTimer);
                pendingLookupTimer = null;
            }

            pendingLookupCell = null;
            pendingLookupRow = null;

            if (lookupDialog.resolve) {
                lookupDialog.close(null);
            } else {
                lookupDialog.destroy();
            }

            grid.destroy();
        }
    };
}
