/**
 * Creates the AMB-owned CRUD facade methods exposed by the public controller.
 *
 * The facade includes report and payload reads, error queries, and targeted or
 * row-scoped application-error management. Every method preserves the
 * semantics of the current `CrudHelper`; it does not reconstruct results,
 * duplicate CRUD behavior or delegate to the internal table engine.
 *
 * @param {object} context - Required method dependencies.
 * @param {CrudHelper} context.crud - Current AMB Grid CRUD layer.
 * @returns {object} CRUD facade methods for the flat controller API.
 * @private
 * @internal
 */
export const createCrudMethods = ({ crud }) => ({
    /**
     * Reads changes currently classified by the AMB CRUD lifecycle.
     *
     * Unlike `getStateReport()`, this returns only inserted, updated and
     * deleted changes. It does not exclude invalid changes automatically or
     * perform validation. The result is returned directly from `CrudHelper`;
     * treat it as a read snapshot and do not mutate it expecting to update AMB
     * Grid state.
     *
     * @returns {{inserted: object[], updated: object[], deleted: object[]}}
     *   Current grouped change set.
     */
    getChanges() {
        return crud.getChanges();
    },

    /**
     * Reads the complete AMB CRUD state report.
     *
     * The report is a broader snapshot than `getChanges()`: it describes rows,
     * lifecycle state, errors, all changes and valid save candidates. It does
     * not run `validate()` and does not convert the report into the focused
     * structure returned by `getSavePayload()`. The result is returned directly
     * from `CrudHelper`; treat it as a read snapshot and do not mutate it
     * expecting to update AMB Grid state.
     *
     * @returns {{
     *   hasChanges: boolean,
     *   hasErrors: boolean,
     *   totalRows: number,
     *   changedRowsCount: number,
     *   errorRowsCount: number,
     *   validChangedRowsCount: number,
     *   invalidChangedRowsCount: number,
     *   rows: object[],
     *   changedRows: object[],
     *   validChangedRows: object[],
     *   invalidChangedRows: object[],
     *   changes: {inserted: object[], updated: object[], deleted: object[]},
     *   validChanges: {inserted: object[], updated: object[], deleted: object[]},
     *   errors: {hasErrors: boolean, rows: object[], cells: object[]}
     * }} Complete AMB Grid state report.
     */
    getStateReport() {
        return crud.getStateReport();
    },

    /**
     * Builds the AMB save payload using the options supported by `CrudHelper`.
     *
     * The supplied options object is forwarded unchanged. Defaults, filtering
     * and payload structure remain owned by `CrudHelper`. This operation does
     * not send the payload, validate rows or mark them as saved. The result is
     * returned directly; treat it as a generated read result and do not mutate
     * it expecting to update AMB Grid state.
     *
     * @param {object} [options] - Save payload options forwarded unchanged.
     * @param {boolean} [options.onlyValid=true] - Use only valid changes.
     * @param {boolean} [options.includeInvalid=false]
     *   Include invalid changed rows in the payload report.
     * @returns {object} Save payload generated by the current CRUD layer.
     */
    getSavePayload(options) {
        return crud.getSavePayload(options);
    },

    /**
     * Reconciles AMB temporary row ids with ids assigned by the backend.
     *
     * Mappings and options are forwarded unchanged to `CrudHelper`, which owns
     * row resolution, duplicate detection, data and snapshot updates, and
     * internal map reconciliation. This method does not send a backend request.
     *
     * A normal application flow is:
     *
     * @example
     * const payload = grid.getSavePayload();
     *
     * const response = await saveRows(payload.changes);
     *
     * grid.applyBackendIds(response.insertedIds);
     * const result = grid.markValidChangesSaved();
     *
     * @param {object[]} mappings - Backend id mappings keyed by temporary id.
     * @param {*} mappings[].tempId - AMB temporary id.
     * @param {*} mappings[].id - Backend id assigned to the row.
     * @param {object} [options] - Reconciliation options forwarded unchanged.
     * @param {boolean} [options.keepTempIdAfterBackendId=false]
     *   Keep the temporary id after assigning the backend id.
     * @returns {{applied: object[], notFound: object[], invalid: object[], duplicates: object[]}}
     *   Result returned directly by `CrudHelper`.
     */
    applyBackendIds(mappings, options) {
        return crud.applyBackendIds(
            mappings,
            options
        );
    },

    /**
     * Confirms one row as saved after a positive backend response.
     *
     * New and modified rows are consolidated; a confirmed deleted row can be
     * physically removed. A new row must receive its backend id before it can
     * be confirmed. The identifier is forwarded unchanged and can be a backend
     * id or `_ambTempId`. This method changes CRUD state but sends no request.
     *
     * @param {*} identifier - Backend id or AMB temporary row id.
     * @returns {boolean} Boolean returned directly by `CrudHelper`.
     */
    markRowSaved(identifier) {
        return crud.markRowSaved(identifier);
    },

    /**
     * Confirms an explicit list of rows after a positive backend response.
     *
     * Identifiers are forwarded unchanged. `true` is returned only when every
     * identifier is handled successfully. The operation is not atomic and
     * provides no group rollback: earlier rows may already be consolidated
     * when a later row fails. This method sends no backend request.
     *
     * @param {Array.<*>} identifiers - Backend or AMB temporary row ids.
     * @returns {boolean} Boolean returned directly by `CrudHelper`.
     */
    markRowsSaved(identifiers) {
        return crud.markRowsSaved(identifiers);
    },

    /**
     * Confirms the valid changes in the current CRUD report.
     *
     * Call this only after the application receives a positive response from
     * its own save request. `CrudHelper` decides which valid changes can be
     * consolidated; new rows without backend ids are skipped. The returned
     * object lists saved and skipped rows. This method sends no backend request.
     *
     * @returns {{saved: object[], skipped: object[]}}
     *   Result returned directly by `CrudHelper`.
     */
    markValidChangesSaved() {
        return crud.markValidChangesSaved();
    },

    /**
     * Reads whether the AMB CRUD layer currently tracks application errors.
     *
     * Both row-level and cell-field errors are included. This does not run
     * `validate()`, clear errors or change messages and markers. CRUD errors
     * can come from AMB validators or application logic and are distinct from
     * the native Cell Component validation state exposed by
     * `getInvalidCells()` and `isCellValid(...)`.
     *
     * @returns {boolean} `true` when a row or cell error is tracked.
     */
    hasErrors() {
        return crud.hasErrors();
    },

    /**
     * Reads the complete summary of errors currently tracked by AMB CRUD.
     *
     * Row errors and cell-field errors remain separated in the `rows` and
     * `cells` arrays. Unlike `getStateReport()`, this focused result does not
     * include rows, lifecycle states, changes or save candidates. Reading it
     * does not validate rows or modify native validation markers, messages or
     * CRUD error state.
     *
     * The result is returned directly from `CrudHelper`; treat it as a read
     * snapshot and do not mutate it expecting to update AMB Grid state.
     *
     * @returns {{hasErrors: boolean, rows: object[], cells: object[]}}
     *   Current grouped CRUD error summary.
     */
    getErrors() {
        return crud.getErrors();
    },

    /**
     * Reads the row-level errors currently tracked by AMB CRUD.
     *
     * Each item contains the available row key, backend id, temporary id, row
     * number and message. An empty array means that no row error is registered.
     * Reading the array does not validate rows, clear messages or modify native
     * validation markers.
     *
     * The array is returned directly from `CrudHelper`; treat it as a read
     * result and do not mutate it expecting to update AMB Grid state.
     *
     * @returns {object[]} Current AMB row errors.
     */
    getRowErrors() {
        return crud.getRowErrors();
    },

    /**
     * Reads the cell-field errors currently tracked by AMB CRUD.
     *
     * Each item contains the available row identifiers, field and message. An
     * empty array means that no cell error is registered. This method does not
     * return native Cell Components and does not read or change their separate
     * runtime validation markers.
     *
     * The array is returned directly from `CrudHelper`; treat it as a read
     * result and do not mutate it expecting to update AMB Grid state.
     *
     * @returns {object[]} Current AMB cell-field errors.
     */
    getCellErrors() {
        return crud.getCellErrors();
    },

    /**
     * Registers an application error for one field of an AMB-managed row.
     *
     * The identifier can be a backend id or `_ambTempId`; identifier, field
     * and message are forwarded without transformation. `CrudHelper` verifies
     * the row and cell, rejects deleted rows, records the error, synchronizes
     * AMB runtime dataset/title attributes and highlighting, and emits the
     * existing CRUD event. The operation does not run validation or change the
     * row lifecycle state.
     *
     * This AMB application error is distinct from native Cell Component
     * validation state. The boolean result is returned directly from
     * `CrudHelper`.
     *
     * @param {*} identifier - Backend id or AMB temporary row id.
     * @param {string} field - Row field receiving the application error.
     * @param {*} message - Error message forwarded unchanged.
     * @returns {boolean} Whether `CrudHelper` applied the cell-field error.
     */
    markCellError(identifier, field, message) {
        return crud.markCellError(
            identifier,
            field,
            message
        );
    },

    /**
     * Clears one AMB application error associated with a row field.
     *
     * The identifier and field are forwarded without transformation.
     * `CrudHelper` owns row resolution, AMB error-map updates, runtime
     * attributes, highlighting and any existing CRUD event. This does not run
     * validation, change lifecycle state or clear the separate native Cell
     * Component validation marker used by `clearCellValidation()`.
     *
     * `true` means the row was found and the operation was handled; it does not
     * guarantee that an error was previously registered for the field.
     *
     * @param {*} identifier - Backend id or AMB temporary row id.
     * @param {string} field - Row field whose application error is cleared.
     * @returns {boolean} Boolean result returned directly by `CrudHelper`.
     */
    clearCellError(identifier, field) {
        return crud.clearCellError(
            identifier,
            field
        );
    },

    /**
     * Registers an application error for an entire AMB-managed row.
     *
     * The backend id or `_ambTempId` and message are forwarded unchanged.
     * Deleted rows cannot receive a new error. `CrudHelper` remains responsible
     * for the AMB error map, runtime row title/dataset attributes, highlighting
     * and the existing `row-error` event. This explicit marker does not replace
     * validation and does not change the row lifecycle state.
     *
     * @param {*} identifier - Backend id or AMB temporary row id.
     * @param {*} message - Row error message forwarded unchanged.
     * @returns {boolean} Whether `CrudHelper` applied the row error.
     */
    markRowError(identifier, message) {
        return crud.markRowError(
            identifier,
            message
        );
    },

    /**
     * Clears only the row-level AMB application error.
     *
     * Cell-field errors for the same row remain registered. `CrudHelper` owns
     * row resolution, runtime attributes and any existing CRUD event. This
     * operation does not modify row data or lifecycle state, run validation or
     * clear native Cell Component validation markers.
     *
     * `true` means the row was found and the operation was handled; it does not
     * guarantee that a row-level error was previously registered.
     *
     * @param {*} identifier - Backend id or AMB temporary row id.
     * @returns {boolean} Boolean result returned directly by `CrudHelper`.
     */
    clearRowError(identifier) {
        return crud.clearRowError(identifier);
    },

    /**
     * Clears every AMB application error associated with fields of one row.
     *
     * The backend id or `_ambTempId` is forwarded unchanged. The general
     * row-level error, if present, remains registered; use
     * `clearErrorsForRow(...)` to clear both levels. `CrudHelper` owns error-map
     * updates, runtime markers, titles, row highlighting and the existing
     * `cell-error-cleared` events.
     *
     * This operation does not run validation, change lifecycle state or clear
     * native Cell Component validation markers. Errors can reappear during a
     * later validation when their underlying condition remains. `true` means
     * the row was found and the cleanup was handled, even when it had no cell
     * errors.
     *
     * @param {*} identifier - Backend id or AMB temporary row id.
     * @returns {boolean} Boolean result returned directly by `CrudHelper`.
     */
    clearCellErrorsForRow(identifier) {
        return crud.clearRowErrors(identifier);
    },

    /**
     * Clears all AMB application errors belonging to one row.
     *
     * Both the general row error and all field errors are removed for the row
     * resolved by backend id or `_ambTempId`; errors belonging to other rows
     * are untouched. `CrudHelper` remains responsible for its error maps,
     * runtime markers/titles, row highlighting and existing cleared events.
     *
     * The operation does not remove or modify validators, run validation,
     * change row data or lifecycle state, or clear native Cell Component
     * validation markers. Errors can reappear during a later validation when
     * their underlying condition remains. The boolean is returned directly
     * from `CrudHelper`.
     *
     * @param {*} identifier - Backend id or AMB temporary row id.
     * @returns {boolean} Whether `CrudHelper` handled cleanup for the row.
     */
    clearErrorsForRow(identifier) {
        return crud.clearAllErrors(identifier);
    }
});
