/**
 * Creates the AMB-owned, read-only CRUD report methods exposed by the public
 * controller.
 *
 * These methods preserve the semantics of the current `CrudHelper`; they do
 * not reconstruct reports or payloads and do not delegate to the internal
 * table engine.
 *
 * @param {object} context - Required method dependencies.
 * @param {CrudHelper} context.crud - Current AMB Grid CRUD layer.
 * @returns {object} CRUD report methods for the flat controller API.
 * @private
 * @internal
 */
export const createCrudMethods = ({ crud }) => ({
    /**
     * Reads changes currently classified by the AMB CRUD lifecycle.
     *
     * Unlike `getStateReport()`, this returns only inserted, updated and
     * deleted changes. It does not exclude invalid changes automatically or
     * perform validation. The result is returned directly from `CrudHelper`;
     * treat it as a read snapshot and do not mutate it expecting to update AMB
     * Grid state.
     *
     * @returns {{inserted: object[], updated: object[], deleted: object[]}}
     *   Current grouped change set.
     */
    getChanges() {
        return crud.getChanges();
    },

    /**
     * Reads the complete AMB CRUD state report.
     *
     * The report is a broader snapshot than `getChanges()`: it describes rows,
     * lifecycle state, errors, all changes and valid save candidates. It does
     * not run `validate()` and does not convert the report into the focused
     * structure returned by `getSavePayload()`. The result is returned directly
     * from `CrudHelper`; treat it as a read snapshot and do not mutate it
     * expecting to update AMB Grid state.
     *
     * @returns {{
     *   hasChanges: boolean,
     *   hasErrors: boolean,
     *   totalRows: number,
     *   changedRowsCount: number,
     *   errorRowsCount: number,
     *   validChangedRowsCount: number,
     *   invalidChangedRowsCount: number,
     *   rows: object[],
     *   changedRows: object[],
     *   validChangedRows: object[],
     *   invalidChangedRows: object[],
     *   changes: {inserted: object[], updated: object[], deleted: object[]},
     *   validChanges: {inserted: object[], updated: object[], deleted: object[]},
     *   errors: {hasErrors: boolean, rows: object[], cells: object[]}
     * }} Complete AMB Grid state report.
     */
    getStateReport() {
        return crud.getStateReport();
    },

    /**
     * Builds the AMB save payload using the options supported by `CrudHelper`.
     *
     * The supplied options object is forwarded unchanged. Defaults, filtering
     * and payload structure remain owned by `CrudHelper`. This operation does
     * not send the payload, validate rows or mark them as saved. The result is
     * returned directly; treat it as a generated read result and do not mutate
     * it expecting to update AMB Grid state.
     *
     * @param {object} [options] - Save payload options forwarded unchanged.
     * @param {boolean} [options.onlyValid=true] - Use only valid changes.
     * @param {boolean} [options.includeInvalid=false]
     *   Include invalid changed rows in the payload report.
     * @returns {object} Save payload generated by the current CRUD layer.
     */
    getSavePayload(options) {
        return crud.getSavePayload(options);
    },

    /**
     * Reads whether the AMB CRUD layer currently tracks application errors.
     *
     * Both row-level and cell-field errors are included. This does not run
     * `validate()`, clear errors or change messages and markers. CRUD errors
     * can come from AMB validators or application logic and are distinct from
     * the native Cell Component validation state exposed by
     * `getInvalidCells()` and `isCellValid(...)`.
     *
     * @returns {boolean} `true` when a row or cell error is tracked.
     */
    hasErrors() {
        return crud.hasErrors();
    },

    /**
     * Reads the complete summary of errors currently tracked by AMB CRUD.
     *
     * Row errors and cell-field errors remain separated in the `rows` and
     * `cells` arrays. Unlike `getStateReport()`, this focused result does not
     * include rows, lifecycle states, changes or save candidates. Reading it
     * does not validate rows or modify native validation markers, messages or
     * CRUD error state.
     *
     * The result is returned directly from `CrudHelper`; treat it as a read
     * snapshot and do not mutate it expecting to update AMB Grid state.
     *
     * @returns {{hasErrors: boolean, rows: object[], cells: object[]}}
     *   Current grouped CRUD error summary.
     */
    getErrors() {
        return crud.getErrors();
    },

    /**
     * Reads the row-level errors currently tracked by AMB CRUD.
     *
     * Each item contains the available row key, backend id, temporary id, row
     * number and message. An empty array means that no row error is registered.
     * Reading the array does not validate rows, clear messages or modify native
     * validation markers.
     *
     * The array is returned directly from `CrudHelper`; treat it as a read
     * result and do not mutate it expecting to update AMB Grid state.
     *
     * @returns {object[]} Current AMB row errors.
     */
    getRowErrors() {
        return crud.getRowErrors();
    },

    /**
     * Reads the cell-field errors currently tracked by AMB CRUD.
     *
     * Each item contains the available row identifiers, field and message. An
     * empty array means that no cell error is registered. This method does not
     * return native Cell Components and does not read or change their separate
     * runtime validation markers.
     *
     * The array is returned directly from `CrudHelper`; treat it as a read
     * result and do not mutate it expecting to update AMB Grid state.
     *
     * @returns {object[]} Current AMB cell-field errors.
     */
    getCellErrors() {
        return crud.getCellErrors();
    }
});
